### ISSUE TITLE
--gpu command doesn't work, Only the default GPU 0 is working

### ISSUE THREAD

**Issue by LiJT** [hlky/stable-diffusion-webui#100]
![1](https://user-images.githubusercontent.com/11270197/187011895-d5685b3b-8406-4837-b49a-9330cc308c1c.png)

Hi maybe am I doing something wrong? Where should I put the prompt?

**Comment by hlky** [comment]
you're doing it wrong

it's a command line argument

follow the same steps [here](https://github.com/hlky/stable-diffusion/blob/main/README.md#want-to-run-full-precision) but add --gpu 1 instead
