### ISSUE TITLE
Option to change saved images location

### ISSUE THREAD

**Issue by athu16** [hlky/stable-diffusion-webui#104]
It would be great if the GUI had an option to enter a path to store the generated images. Right now the only way I can think of is to change the hard-coded path in the code, which can be a bit hard for novice users.

By the way thanks a lot for this awesome tool!

**Comment by EyeDeck** [comment]
Not a great idea to expose that to the web UI, an unauthorized user/troll could start writing to OS dirs or whatever and make an annoying mess.

Right now you can pass `--outdir [path]` to webui.py for both txt2img and img2img,
or `--outdir_txt2img [path]` / `--outdir_img2img [path]` if you prefer.
If you're using the relauncher.py script, you can by set them by tweaking the os.system line like so:
```python
    os.system('python scripts/webui.py --outdir_txt2img "E:/AI/SD-gradio/txt/" --outdir_img2img "E:/AI/SD-gradio/img/"')
```

**Comment by athu16** [comment]
Right, didn't think of that. Thanks a lot!
