### ISSUE TITLE
Masking Selection Falls off after a couple uses

### ISSUE THREAD

**Issue by heartlocket** [hlky/stable-diffusion-webui#105]
My img2img mask selection disappears after I do a few runs, forcing me to repaint when i want to try different prompts. Not sure if this is intended?

Also, the masking workflow is great but would be 100x more efficient with a slider for palette size of the mask brush. it takes ages to mask because the default brush is tiny.

**Comment by hlky** [comment]
Advanced editor / mask and crop feature is highly temperamental and small bugs are to be expected

Are you sure the mask actually disappears? The workaround for many bugs with mask and crop is to switch to crop and back to mask or switch to mask and back to crop.

The advanced editor might be useable on mask mode at some point.

Alternatively, as you are doing the same mask many times, you may wish to just apply the mask in something like photoshop or [photopea](https://www.photopea.com/) it's simply a gaussian blur, i believe 3px

**Comment by heartlocket** [comment]
ah i just checked the ui photos and i see i am working on a day-old version. i will have to update and see if it works. i do not have mask/crop yet, just the previous build that had 'img2img' as the tab title no 'unified'
