### ISSUE TITLE
Write correct per file seed into "Write sample info" files for batch generation

### ISSUE THREAD

**Issue by cgmind** [hlky/stable-diffusion-webui#109]
<s>Currently there isn't (I believe) any way to get the seed used in subsequent images during a batch or sample.  Some sort of option to either get the seed from each output of a batch job, or set the seed to something consistent like seed + n per batch would be great.</s>

Actually it is just the yaml files produced when you use "Write sample info files" that writes the original seed in every file instead of the incremented one, the file name has the correct seed.

**Comment by JohannesGaessler** [comment]
Does getting the seeds from the info files not work for you?

**Comment by EyeDeck** [comment]
Not sure if I'm reading this wrong, but it _should_ already work that way, at least it does for me. If you make a batch of 10 images with a seed of '10', (and it shouldn't matter if that's 10 iterations@1 sample, 5@2, or 2@5, etc) the first image's seed should be 10, then 11, and so on up to 20.

**Comment by hlky** [comment]
Correct seed is already written to file, I suspect it always ways.
