### ISSUE TITLE
The new generate are overwrites the previews generate that are on the same seed (must fix) thanks!

### ISSUE THREAD

**Issue by search620** [hlky/stable-diffusion-webui#116]

**Comment by hlky** [comment]
with save by prompt:
`f"{base_count:05}-{steps}_{sampler_name}_{seeds[i]}"`

without:
`f"{base_count:05}-{steps}_{sampler_name}_{seeds[i]}_{sanitized_prompt}"[:128]

base_count = number of files in the folder

so this can't happen
