### ISSUE TITLE
Compatibility with latest Optimized version

### ISSUE THREAD

**Issue by Michoko92** [hlky/stable-diffusion-webui#119]
HI,

First, thank you so much for your awesome work on this fork. As an RTX 2060 owner, I also appreciate the fact you included optimizations from basujindal's repo. However, Basu pushed a pretty amazing update yesterday, making SD work beautifully on 6 GB cards. Basically, now, you just have a --turbo toggle that will make fewer splits of the model (no more --small_batch arguments too)

So if you use the script without the --turbo argument, the model will be split into 4 parts like before, approx. doubling the required time to make an image. But it then works on 4 GB VRAM cards. This is the current implementation you have in your webUI too.
However, with the new --turbo toggle, the model is split into fewer parts, still fitting into 6 GB of VRAM, but then being as fast as other regular repos, like Waifu's. So it's the best of both worlds, and I can go up to 576x768 resolution full speed on my RTX 2060 which is awesome! Also, it's as fast as a regular T4 Google colab.

I tried to adapt your latest "Optimized" changes to work with the latest version of basujindal's scripts, but my ignorance of Python made me hit a wall. Do you think you'd be willing to include this great feature, please? Like --optimize6GB or something that feels relevant to you? Thank you!

**Comment by AbdBarho** [comment]
@Michoko92 could please link to the latest basujindal version you are talking about? Maybe I can give it a look and see if it is easy to merge

**Comment by Jpkovas** [comment]
> 

https://github.com/basujindal/stable-diffusion

**Comment by Michoko92** [comment]
Thank you for your reply. It is actually the last available version at https://github.com/basujindal/stable-diffusion/tree/main/optimizedSD (most of the scripts were updated).

The main change is that the --small_batch argument was removed, and the --turbo argument was added. This --turbo argument lowers the number of splits applied to the model when doing computations.

**Comment by Michoko92** [comment]
Also the link to the issue that talks about it, to give you context: https://github.com/basujindal/stable-diffusion/issues/69

**Comment by AbdBarho** [comment]
@Michoko92 it seems that the two repos have diverged much more that I expected, I also hit a wall...

I guess it is still possible to add the turbo feature, with some work. btw. I am running GTX 1060 6GB so I would also like this, but oh well...

Still, I find it very fascinating how much changes happened within one week, and how much each of the forks has grew 👏

**Comment by Michoko92** [comment]
Yeah, it's a bit tricky, I guess. I think that @hlky is the man here, as he recently already merged the previous optimizedSD code with his repo, so it might be fresh enough for him (hopefully) :)

Me too, I would absolutely love to see such a powerful improvement applied to his great UI and modules (additional samplers, inpainting, upscalers... so many cool features!)

**Comment by hlky** [comment]
Idk

**Comment by hlky** [comment]
`Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

**Comment by hlky** [comment]
needs ddpm.py from basujindal in optimizedsd folder to test this i'm still working on it starting again though from current master

**Comment by Michoko92** [comment]
This is awesome news, thank you so much! Yes I think that the script you first merged in issue #97 may have been a hack of a former basujindal's implementation. So starting again from the master should be much cleaner. Thanks again, your efforts are extremely appreciated 🙏

**Comment by hlky** [comment]
To clarify, img2img still doesn't work in master, to test the above branch you also need the inference.yaml from basujindal

When working on it I got a few different errors along the way but the main two toward the end were about tensors on two devices, something must be messed in the code copied from basujindal  because the optimization requires a lot of switching between cpu and cuda, and it's not quite a straight copy because this repo has moved a lot of things around.

The current implementation in this repo is merged together from a pastebin.com post but there were conflicts with master because i didnt' know which commit it was based on, kinda awkward

**Comment by Michoko92** [comment]
Please tell me if I can help with testing or anything.

**Comment by hlky** [comment]
https://github.com/hlky/stable-diffusion-webui/wiki/Optimized-mode

**Comment by Michoko92** [comment]
Thank you for looking into it :)

**Comment by Michoko92** [comment]
Thank you so much to @interficiam for finally fixing it! So awesome to be able to use all those great features on a 6 BG cards! <3

**Comment by DenkingOfficial** [comment]
I think optimized mode is not working atm
I'm getting error while generation after downloading latest version from master branch
`Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
