### ISSUE TITLE
img2img uses only 2 samplers.

### ISSUE THREAD

**Issue by ivdos** [hlky/stable-diffusion-webui#125]
Img2img uses only 2 samplers k_lms and DIMM. The rest are not used.

**Comment by hlky** [comment]
```
if sampler_name == 'DDIM':
        sampler = DDIMSampler(model)
    elif sampler_name == 'k_dpm_2_a':
        sampler = KDiffusionSampler(model,'dpm_2_ancestral')
    elif sampler_name == 'k_dpm_2':
        sampler = KDiffusionSampler(model,'dpm_2')
    elif sampler_name == 'k_euler_a':
        sampler = KDiffusionSampler(model,'euler_ancestral')
    elif sampler_name == 'k_euler':
        sampler = KDiffusionSampler(model,'euler')
    elif sampler_name == 'k_heun':
        sampler = KDiffusionSampler(model,'heun')
    elif sampler_name == 'k_lms':
        sampler = KDiffusionSampler(model,'lms')
```
sampler is set

**Comment by ivdos** [comment]
> sampler is set
Yes they are set up, but only two are used:
`if sampler_name != 'DDIM':
            x0, = init_data

            sigmas = sampler.model_wrap.get_sigmas(ddim_steps)
            noise = x * sigmas[ddim_steps - t_enc - 1]

            xi = x0 + noise
            sigma_sched = sigmas[ddim_steps - t_enc - 1:]
            model_wrap_cfg = CFGDenoiser(sampler.model_wrap)
            samples_ddim = K.sampling.sample_lms(model_wrap_cfg, xi, sigma_sched, extra_args={'cond': conditioning, 'uncond': unconditional_conditioning, 'cond_scale': cfg_scale}, disable=False)`
The last line

**Comment by hlky** [comment]
Fixed, I'm seeing duplicate output images with only batch size 1, not sure if this caused it but i dont see why it would, possibly pre-existing, not sure

**Comment by ivdos** [comment]
Now the sampler just works as txt2img. I added the get_sampler_name function to the KDiffusionSampler class. To get the name of the sampler:

```
def get_sampler_name(self):
        return self.schedule
```
And in the sample function
```samples_ddim = K.sampling.__dict__[f'sample_{sampler.get_sampler_name()}'](model_wrap_cfg, xi, sigma_sched, extra_args={'cond': conditioning, 'uncond': unconditional_conditioning, 'cond_scale': cfg_scale}, disable=False)```
