### ISSUE TITLE
Some features suggestion + features toggles bug

### ISSUE THREAD

**Issue by htkg** [hlky/stable-diffusion-webui#127]
![image](https://user-images.githubusercontent.com/18707625/187033695-fe1f9b9f-38a5-446e-b16f-888e5be8c82c.png)

I'm trying to disable some features (Sort samples by prompt, Write sample info files) however those persist being defaults in the web interface.

**Suggestions**

- Make `ddim_eta` visible by default or make an option in the yaml file. I have no idea why it was hidden, however each time I update I need to edit the Python file to make it visible
- Make an option in the GUI interface to imprint sample info into the EXIF of the files, instead of writting into the separate file.
- Make an option to disable saving original/GFPGAN copies or maybe save it in the separate folders dunno. It's kinda uncomfortable now to receive bunch of images: information file, sample without GFPGAN, sample with GFPGAN. I liked that it saved the GFPGAN (if used) sample instead of original one before.

**Stupid question**

I've used before a version from the yesterday. Is the optimization and model precision changed? I'm getting slightly lower quality images than I've used to get before or maybe I am unlucky today.

Thank you for the hard work on this fork!

**Comment by hlky** [comment]
> I have no idea why it was hidden

unused 

>EXIF of the files,

It is for png

> disable saving original/GFPGAN

Just run gfpgan separately then, it is assumed if you tick gfpgan on generation you want before and after, how else are you meant to know the difference?

These are all non-issues imo that aren't high priority for me to fix, yet they are so simple you could have done it yourself in the time it took you to make this issue

**Comment by htkg** [comment]
as you say
all of those suggestions are just QoL / my IMO and not important
