### ISSUE TITLE
[Feature suggestion] Automatically enable prompt matrix when the prompt contains "|"

### ISSUE THREAD

**Issue by nahojjjen** [hlky/stable-diffusion-webui#128]
Pros:
- Can remove a setting & slightly clean up UI 
- Makes it easier to switch between creating matrices and normal batches as you don't need to remember the switch

Cons:
- Decreases discoverability of the feature
- Makes it impossible to create prompts with "|"

**Comment by lendrick** [comment]
Please don't do this.

**Comment by nahojjjen** [comment]
For me it would be a QOL upgrade, and I assumed it would be for most other people as well. Do you have a specific usecase / idea as for why this would be a bad idea?
@lendrick

**Comment by nahojjjen** [comment]
I've added this change to my local webui.py  (except I havent removed the ui-toggle), and it works well for me.

**Comment by ZeroCool940711** [comment]
@nahojjjen some people might want to use multi-line prompts and also some people use the `|` character to split the prompts and add extra details to the generation, things that are meant to enhance the main prompt but are not part of the prompt itself, for some reason that character do help to do that when other characters like commas or periods have less priority, it's similar to weighted prompts.

**Comment by hlky** [comment]
#180 just implemented this as part of grid fixes. I can revert those changes if you know of people actually using | in prompts as a word separator like , . etc

**Comment by lendrick** [comment]
@hlky At least add a checkbox that lets me turn it off.  It'll break all of my prompts.

**Comment by hlky** [comment]
No it's fine, I had saw others using it like you tbh, I was dubious about the feature too

Closing this is as we won't fix it, just remember to enable prompt matrix if you want to use it

**Comment by hlky** [comment]
Changes are reverted btw @lendrick let me know if there's still an issue

See readme for info on the other feature #180 added, tl;dr don't start your prompts with @

**Comment by ZeroCool940711** [comment]
btw, @hlky I think you should add on the wiki or somewhere that info I just mentioned of using `|` to enhance prompts, as I said, it does make images a lot better than using a comma for extra details, for example, here is a 1:1 comparison using the same seed and same parameters and everything but changing the `,` for a `|` in the prompt:

 "A lake in the mountains , unreal engine" 
![00000-100_k_lms_0-gfpgan-esrgan4x (2)](https://user-images.githubusercontent.com/5977640/187080617-7dcf9955-d3d1-44a5-8c01-fc0f1a75ad7d.png)
![00001-100_k_lms_1-gfpgan-esrgan4x (2)](https://user-images.githubusercontent.com/5977640/187080627-41312a93-facd-4e90-85c5-5ecdd75b37e7.png)
![00002-100_k_lms_2-gfpgan-esrgan4x (2)](https://user-images.githubusercontent.com/5977640/187080633-6ad7690a-198e-4883-9b6b-3f3be9027c0e.png)

 "A lake in the mountains | unreal engine" 

![00000-100_k_lms_0-gfpgan-esrgan4x](https://user-images.githubusercontent.com/5977640/187080654-e5a51871-9776-4cdf-b84f-3fab3ad30bb5.png)
![00001-100_k_lms_1-gfpgan-esrgan4x](https://user-images.githubusercontent.com/5977640/187080658-4acafef3-06de-49ca-980e-8adc1130cb23.png)
![00002-100_k_lms_2-gfpgan-esrgan4x](https://user-images.githubusercontent.com/5977640/187080666-8bd410ea-6627-4f8a-ad24-dffe2b2de827.png)

As you can probably see the second prompt using the `|` give a lot better results than the other one, when using multiple words and using the `|` character as separator every word enhances the main prompt and when using a comma everything is taken as a single prompt.

**Comment by nahojjjen** [comment]
I see, then I absolutely agree, removing a usable symbol is not acceptable.

**Comment by lendrick** [comment]
@hlky Not seeing any issue.
