### ISSUE TITLE
Add setup.py, requirements.txt, other installation help

### ISSUE THREAD

**Issue by Jurph** [hlky/stable-diffusion-webui#129]
Most hobbyists in this space are comfortable banging on a python script and `pip install`ing whatever is missing through iteratively running the script until it runs... but this is frustrating and will turn hobbyists away from this awesome and otherwise accessible project. Consider adding installation instructions to the `README.md`,  a `setup.py` file, or a `requirements.txt` / `environment.yml` so that `pip` and `conda` users can get it running quickly.

**Comment by nahojjjen** [comment]
I don't think this repo is intended to be ran by users directly, rather users are supposed to use https://rentry.org/GUItard , and only download the files here and insert them manually if they want to try features still in development. But I might be completely wrong :) It's a bit unclear, the project is still very new. 

If my interpretation is right, maybe there should be a link to the installation guide in the readme.

**Comment by Jurph** [comment]
Yeah, literally any documentation at all about the _intent_ of this repo would help -- "Hey, don't run this directly, go to the rentry.org link" would be nice.

**Comment by AbdBarho** [comment]
I have tried packaging this with docker so it becomes much easier to install and use, you can check it out here:

https://github.com/AbdBarho/stable-diffusion-webui-docker

Hope it helps!

**Comment by hlky** [comment]
> Yeah, literally any documentation at all about the _intent_ of this repo would help -- "Hey, don't run this directly, go to the rentry.org link" would be nice.

pebkac
look at the other repo
