### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by loretoparisi** [hlky/stable-diffusion-webui#136]
Thanks for this amazing work!
Sorry, I'm a bit confused how to install the webui and libraries requirements, I was looking at 
https://rentry.org/kretard and here https://github.com/AUTOMATIC1111/stable-diffusion-webui
but instructions and dependencies seems to be slightly different.

Thank you!

**Comment by AbdBarho** [comment]
Hi!

Just for your info, this is the development version of the UI and it is unstable.

Assuming you have setup everything according to https://rentry.org/GUItard and you are able to run the base version, you should be able to integrate the changes here easily. Basically download this repository and copy / overwrite files, the mapping be found here:

https://github.com/hlky/stable-diffusion-webui/blob/master/.github/sync.yml

Then run as usual!

Hope it helps.

**Comment by jansteffen** [comment]
Look at what it says right at the very top of https://rentry.org/kretard

> This guide has been replaced

Hmm I wonder what that could mean

**Comment by hlky** [comment]
Readme updated
