### ISSUE TITLE
"Copy-paste generation parameters" field appears to erroneously report that a prompt was truncated when using long multiple weighted prompts

### ISSUE THREAD

**Issue by lendrick** [hlky/stable-diffusion-webui#139]
When I'm using multiple long weighted prompts, the prompts work correctly, but the "Copy-paste generation parameters" box warns that the prompt was truncated, even if I'm using two prompts that are each below the truncation threshold.

Steps to reproduce:

Enter this prompt: "A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A digital painting of a swiss cheese wheel, by greg manchess, trending on artstation:200"

Note that it will generate a cheese wheel (or a wheel made of cheese), as one would expect from the prompt weights.  However, the generation parameters field reads as follows:

> 
> A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation:1 A digital painting of a swiss cheese wheel, by greg manchess, trending on artstation:200
> Steps: 51, Sampler: k_lms, CFG scale: 16, Seed: 1618836146, RealESRGAN_x4plus
> 
> Warning: too many input tokens; some (83) have been truncated:
> , shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade , trending on artstation : 1 a beautiful painting of a singular lighthouse , shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade , trending on artstation : 1 a digital painting of a swiss cheese wheel , by greg manchess , trending on artstation : 2 0 0
>

**Comment by hlky** [comment]
too many input tokens

**Comment by lendrick** [comment]
Did you test my prompt and see the cheese generate?
