### ISSUE TITLE
[FEATURE REQUEST] Reduce noise overtime with loopback

### ISSUE THREAD

**Issue by Savager3435** [hlky/stable-diffusion-webui#144]
**Is your feature request related to a problem? Please describe.**
When using the "loopback" feature over time images can become overly stylized. For example if you were to say 1970s photo it would eventually exasperate the effects of the style- oversaturated, very heavy color filters etc

**Proposed Solution**
My proposed solution would be to add an option to reduce the noise applied to each successive image. For example you might start with the noise at 0.8 but by the last image it would be down to 0.3. 
I think the best way to implement such a feature would be to add a checkbox for this feature and 2 input fields. One for the amount of noise for the initial image, one for the amount of noise added on the last image. Then noise would be gradually reduced with each generation

**Additional context**
Attached is an example of how it currently, over stylizes the images due to the consistent noise.
I overdid the effect to make it easier to explain, by increasing the amount of noise.
The first image is the inital image used, and the second is the result after a few generations with loopback.
![image](https://user-images.githubusercontent.com/38446179/187043233-99f3e81c-e191-464f-bbe2-a080197c8962.png)

![00010-2754865346](https://user-images.githubusercontent.com/38446179/187043199-2e75851d-94e0-47f2-9b30-b05ba5041350.png)

**Comment by DustyCooper** [comment]
There's a lot of learning that we're all having to do right now. Not sure a check box would cut it with some pre-determined strength reduction. I'm even hesitant to automatically loopback generations because they may need tweaking or multiple rolls to get what I'm looking for.

**Comment by hlky** [comment]
> might start with the noise at 0.8 

That's not how you use loopback, you start a lot lower than that

https://github.com/hlky/stable-diffusion-webui#loopback

It's not really intended to provide good results

As @DustyCooper said you should do it yourself manually for best results, generate several samples, choose the best, and run again

**Comment by Savager3435** [comment]
Fair enough, just thought it could reduce the number of generations needed to transform something rudimentary, into a better image.  Didn't really consider doing it manually, thank you 👍 

As far as loopback being of questionable usefulness, I see why someone would say that as you're gambling with the quality of output, but I think it's interesting throwing an image in with like .4-.7 noise and letting it make 20 generations. As long as you can make a halfway decent prompt it does pretty well. 
 It's fun to see how prompts affect things unintentionally and how the images slowly change over time.
