### ISSUE TITLE
[BUG]cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by alexfredo** [hlky/stable-diffusion-webui#146]
Hi when I click on generate I have this bug : cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
Please help me  !! thanks

**Comment by hlky** [comment]
@alexfredo there is a template for a reason, it helps people to fix your issue

What operating system?
What graphics card do you have?
Are you using --optimized?

**Comment by alexfredo** [comment]
I have windows 10
geforce rtx 2060
I don't use --optimized

**Comment by alexfredo** [comment]
How I can use --optimized ?

**Comment by hlky** [comment]
Look at the readme

**Comment by hlky** [comment]
Closing because unreproducible for now, seems to be hardware issue, and not enough information provided
