### ISSUE TITLE
[BUG] Duplicated samples displayed in output of img2img

### ISSUE THREAD

**Issue by hlky** [hlky/stable-diffusion-webui#147]
**Describe the bug**
Duplicate samples displayed in output of img2img

**To Reproduce**
1. generate img2img sample
2. see error

**Expected behavior**
Displayed outputs are not duplicated

**Screenshots**
![image](https://user-images.githubusercontent.com/106811348/187043722-455c34c4-484d-4e65-8d1c-c39c24822ee0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version master

**Comment by AbdBarho** [comment]
One of them is the grid, the other one is the image.

If you increase the number of samples to 2 or more, you will see the difference.

![image](https://user-images.githubusercontent.com/24505302/187044180-130f23d5-a47f-41aa-bd9c-90f5efd8239b.png)

**Comment by hlky** [comment]
Ah, just needs documenting then
