### ISSUE TITLE
[BUG] default settings generates 2 identical images

### ISSUE THREAD

**Issue by altryne** [hlky/stable-diffusion-webui#148]
**Describe the bug**
Updated to the latest version, and submitting 1 prompt with 1 batch count returns 2 of the same image. 

**To Reproduce**
1. submit a prompt

**Expected behavior**
1 image appears

**Screenshots**
![CleanShot 2022-08-27 at 12 35 50@2x](https://user-images.githubusercontent.com/463317/187043756-5608404f-1ac5-4469-982e-2c5bbe061322.jpg)

**Additional context**
Could be related to the grid changes? 
Unchecking 'save grid' fixes this

**Comment by hlky** [comment]
See #147 as well

> Unchecking 'save grid' fixes this

Thanks, this should narrow it down

**Comment by altryne** [comment]
could be related to #147
