### ISSUE TITLE
[BUG] - generating with matrix shows an error IndexError: list index out of range

### ISSUE THREAD

**Issue by altryne** [hlky/stable-diffusion-webui#149]
**Describe the bug**
Error on generating with matrix separators 

**To Reproduce**
1. add prompt `a corgi in a forest | by greg rutkowski | by studio ghibli`
2. Images are generated find and are stored in outputs folder
3. UI shows an error (screenshots) 

**Expected behavior**
Images show in gallery

**Screenshots**
![CleanShot 2022-08-27 at 12 42 29@2x](https://user-images.githubusercontent.com/463317/187043987-73668e5e-da3f-4de6-a7ba-340f00bfca9c.jpg)

**Additional context**
Probably grid related

**Comment by hlky** [comment]
#140  ?

**Comment by hlky** [comment]
@altryne reopen if not fixed

**Comment by HenkDz** [comment]
@hlky I am getting this error on img2img tab after the latest update. I pulled from main and added webui on top of it.

![image](https://user-images.githubusercontent.com/17301927/187424484-abd4788e-b815-4a1a-bf13-f26b5de6f133.png)

**Comment by hlky** [comment]
@HenkDz what exactly are you trying to do in img2img?
