### ISSUE TITLE
Where are the installation instructions?

### ISSUE THREAD

**Issue by bibyts** [hlky/stable-diffusion-webui#153]
How to install this repo?

**Comment by nahojjjen** [comment]
This is a repo for development, the installable 'stable' release is here:

https://github.com/hlky/stable-diffusion

**Comment by hlky** [comment]
![image](https://user-images.githubusercontent.com/106811348/187046897-6768b1a9-3eb3-4dc3-a827-b0e5aabe6f2f.png)

**Comment by bibyts** [comment]
Thanks.
