### ISSUE TITLE
[BUG] The GFPGAN seem not to work with RealESRGAN at the same time

### ISSUE THREAD

**Issue by search620** [hlky/stable-diffusion-webui#158]
The GFPGAN seems not to work with RealESRGAN at the same time (the export produce the upscale image without the face correction)

Except for this bug, I highly recommend that export will be in two different folders "Grid" and "samples"
and add to that in the sample folder the "info file" should be in a separate folder in the same directory as "prompt info" or something.

It's a bit annoying and confusing to the eye to see all these files next to each other.

**Comment by search620** [comment]
also, the export produce 3 images instead of 1

**Comment by hlky** [comment]
```
[f19029a](https://github.com/hlky/stable-diffusion-webui/commit/f19029aa6b82ad9d44c4069167803a3d1575217a)

At most should produce 2 samples
>original & gfpgan
>original & esrgan
>original & gfpgan -> esrgan

Turn off save individual samples to save only gfpgan, esrgan or gfpgan -> esrgan
```

>GFPGAN seems not to work with RealESRGAN

Good catch, testing a fix for this now, gfpgan itself was actually broken by the author of the recent GoBIG implementation, but the sample also wasn't passed correctly when both gfpgan and esrgan are enabled

```
Except for this bug, I highly recommend that export will be in two different folders "Grid" and "samples"
and add to that in the sample folder the "info file" should be in a separate folder in the same directory as "prompt info" or something.```

Are you referring to when the sort samples by prompt option and the write sample info option are enabled? The grid shouldn't be saving in \samples\<prompt named folder>, it will have saved ..\ from \samples
