### ISSUE TITLE
[BUG] Crash in full precision - txt2img expected scalar type Half but found Float

### ISSUE THREAD

**Issue by Oceanswave** [hlky/stable-diffusion-webui#161]
**Describe the bug**
When --precision full, txt2img crashes with the message 'expected scalar type Half but found Float'

**To Reproduce**
1. Launch with --precision full
2. execute a prompt

**Expected behavior**
No crash in full mode

**Desktop (please complete the following information):**
- Ubuntu 20.04

**Comment by hlky** [comment]
[Want to run full precision?](https://github.com/hlky/stable-diffusion#want-to-run-full-precision)
Edit `scripts\relauncher.py` `python scripts/webui.py` becomes `python scripts/webui.py --no-half --precision=full`

Both --no-half and --precision full are required
