### ISSUE TITLE
[BUG] Gradio error when generating Img2Img

### ISSUE THREAD

**Issue by xblt** [hlky/stable-diffusion-webui#169]
![Screenshot 2022-08-27 180432](https://user-images.githubusercontent.com/112146913/187053416-b0d3a848-2dc9-4363-94bb-7388baf2feb4.png)

**Describe the bug**
When trying to generate an image with Img2Img, error occurs. Did not change any of the default options. 

**To Reproduce**
1. Uploaded an image into the editor
2. Wrote a basic sentence in the prompt
3. Hit generate
4. Error. 

**Desktop (please complete the following information):**
Windows 10, Chrome Browser.

**Comment by hlky** [comment]
gobig implentation is trash, reverted, download again

also, as stated in many places 

### This repo is for development, there may be bugs and new features
