### ISSUE TITLE
[FEATURE REQUEST] SwinIR-L 4x

### ISSUE THREAD

**Issue by darkstorm2150** [hlky/stable-diffusion-webui#171]
I would be great to have SwinIR-L 4x built-in, The results compared to ESRGAN are much better (discord link with example of how it works) https://discord.gg/8KCZSeFw

The results are like day and night.

**Comment by hlky** [comment]
https://github.com/hlky/stable-diffusion-webui/wiki/Upscalers

**Comment by asimard1** [comment]
@darkstorm2150 Link is dead, maybe provide a direct image?
