### ISSUE TITLE
[BUG] Text in the CFG Description jitters when the scale goes above 10

### ISSUE THREAD

**Issue by JoshuaKimsey** [hlky/stable-diffusion-webui#172]
**Describe the bug**
Text in the CFG description area jitters when the number representing it goes above 10, and switches between a decimal point and a whole number.

**To Reproduce**
1. Go to CFG area
2. Slide the bar to be above 10
3. Go between a whole and decimal number
4. The text describing what the CFG is will jitter

**Screenshots**
See below

**Desktop (please complete the following information):**
 - OS: Linux Pop!_OS 22.04
 - Browser: Brave
 - Version: v1.42.97

**Additional context**
This may be solved by just always showing the decimal point, even if it is 0.
![Screenshot from 2022-08-27 22-46-35](https://user-images.githubusercontent.com/22421310/187055393-d83947ad-cdba-4633-8997-c16e3493f6c1.png)
![Screenshot from 2022-08-27 22-46-42](https://user-images.githubusercontent.com/22421310/187055394-ce3d7033-5a67-414a-a936-5026846fb342.png)

**Comment by hlky** [comment]
I think this could be fixed with css

**Comment by hlky** [comment]
Nope, not possible right now from what I can tell.
