### ISSUE TITLE
[BUG] Automatic GFPGAN option doesnt work.

### ISSUE THREAD

**Issue by HighOnBuffs** [hlky/stable-diffusion-webui#174]
**Describe the bug**
When using (ticking the box) the automatic GFPGAN option it doesnt restore faces. It tells me it does but the pictures are untouched. When i upload it in the separate tab and use it it works although it doesnt save the picture anywhere.

**To Reproduce**
Tick the GFPGAN box under advanced settings in txt2img

**Expected behavior**
Like the other version i was using before to automatically apply GFPGAN face restore to the pictures. Also a slider with intensity would be very nice for the automatic GFPGAN.

**Comment by hlky** [comment]
https://github.com/hlky/stable-diffusion-webui/wiki/Upscalers
