### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Alexadar** [hlky/stable-diffusion-webui#186]
Hi! 
I would like to request license for commercial use
Thanks!

**Comment by hlky** [comment]
This project isn't in a state ready for commercial use. Plus the additional support required on my end to deal with all your commercial users considering you probably don't want to pay for the license, and probably want to be able to rely solely on this repo for new features etc probably without even contributing back. Therefore

# NO commercial usage allowed

I assume if you meant anything different you would have clarified to begin with

**Comment by Alexadar** [comment]
Roger man. Anyway, gj on assembling everything in one app!
