### ISSUE TITLE
[BUG] "Select image number from results for copying" works neither in txt2img nor img2img

### ISSUE THREAD

**Issue by Alphyn-gunner** [hlky/stable-diffusion-webui#192]
In stable version:
![image](https://user-images.githubusercontent.com/34932866/187075869-b56f8e4e-17ca-4b3d-90c4-118d1122abff.png)
The text field that was used to select the image to copy to img2img is not editable anymore and it's impossible to select an image from the batch.

**Comment by hlky** [comment]
#166 related I think

@altryne did this, wait for his reply

**Comment by altryne** [comment]
I think that disabled field was a result of a merge, and is technically not needed since we use JS to figure out the right image. 

I'll take a look soon, meanwhile, are there any JS errors in browser console? 

Also, what browser and OS are you running?

**Comment by butch2k** [comment]
I tested several chromium based browser same issue: chrome, brave, Edge, i did not test Safari nor FF yet
Clicking on Copy to Clipboard
![image](https://user-images.githubusercontent.com/961507/187081495-143cde7a-60c0-49a0-843b-472f0e8d7790.png)

**Comment by jansteffen** [comment]
Yeah. looking at the code right now the newer buttons that push the selected image from the gallery via Javascript used the same name as that "select number then copy" and also changed some of the methods, so now the old ones no longer work.

But I agree with @altryne, we don't actually need them anymore.

I happen to be working on a small revamp for that output area right now, so I could go ahead and remove those old ones completely (give me another ~30 mins for a PR)

![image](https://user-images.githubusercontent.com/1278331/187081476-d0aaefe1-54f3-4baf-b920-06aafdc5575f.png)


![image](https://user-images.githubusercontent.com/1278331/187081473-0f7d0f65-ef20-40ce-8bae-94400ca9570c.png)

**Comment by altryne** [comment]
@jansteffen thanks, I came on and there's a lot of changes I need to merge 😓 😅  
@hlky can we be added as collaborators so we can review and assign PRs ?

**Comment by jansteffen** [comment]
sorry it took longer than expected, I kept fucking up the sync for my repo lol

Anyways PR is up #196

**Comment by hlky** [comment]
Good work both of you, thanks!

**Comment by jansteffen** [comment]
One thing I wasn't able to implement was making it so the output area is completely hidden on page load and only appears after generating an image, but for some reason the `gr.Column()` element just refused to listen to `gr.Update(visible=True)`. Maybe someone else can have a look at that, or it's another bug with Gradio...

**Comment by Alphyn-gunner** [comment]
Thank you everyone! I wish I knew more Python or JS to help you more, but at least I can test things.

Here's my report:
- I see new neat tabs in both modes.
- In txt mode push to img2img works fine now.
- The Upscale w/ ESRGAN button still does nothing.
- In the Img2img mode old behavior, the number is still not editable, the button pushes the grid now, since it's the first image.

**Comment by Alphyn-gunner** [comment]
It actually got much worse in the img2img. 

Trying to push an image in img2img after clearing the input image killed the entire process for me twice now. The CMD window just disappears.

**Comment by jansteffen** [comment]
Hmm I'm unfortunately busy right now but I can have another look in an hour or two but I could swear it worked fine for me. What browser are you using @Alphyn-gunner?

**Comment by Alphyn-gunner** [comment]
Latest Chrome (104.0.5112.102) on Windows 10.

**Comment by Alphyn-gunner** [comment]
It looks like neither `output_txt2img_to_upscale_esrgan` nor `output_img2img_select_image` are implemented? The buttons are the only places those names are referenced in the code.

**Comment by jansteffen** [comment]
Ok it looks like when those fancy new Javascript buttons got added the old implementation was completely overwritten and is no longer present. The "copy selected image to input" button on the img2img tab inadvertantly calls the new javascript implementation, and I think that code always looks at which image is selected on the txt2img tab, even when you're currently using the img2img tab.

Unfortunately said JavaScript code looks like some cthulu monstrosity so I don't really know how to fix it.

Temporary band-aid solutions would be completely removing those buttons from img2img in the assumption that we'll add "better" buttons soon, or trying to restore the old functionality, but I'd have to go digging into older versions of the code for that.

@altryne thoughts? Also, should we reopen this issue or create a new one?

**Comment by altryne** [comment]
Yeah the JS there is teeth cutting isn't it? 
Kids wen't to sleep, I'm taking a look now.

**Comment by nderscore** [comment]
I forgot to check the issues and missed this, but I think I might #203 should fix at least fix the loopback buttons (`-> img2img`) for now.

**Comment by altryne** [comment]
@nderscore I checked it out and there seems to be a few issues, going refactor a bit. Thanks for simplifying down the JS

**Comment by jansteffen** [comment]
Indeed it does! Thanks for that, however now it also automatically switches the editor to mask mode every time? Looks like it's caused by very intentional looking line

`root.querySelector('#img2img_editor')?.parentNode.querySelector('input[type="radio"][value="Mask"]')?.click();`

but I don't think behavior is what we actually want?

**Comment by nderscore** [comment]
> however now it also automatically switches the editor to mask mode every time

That's a bad assumption on my part. I figured masking was a more common use case than cropping/resizing, without thinking about how the advanced editor tools were also in there :facepalm:

**Comment by jansteffen** [comment]
@nderscore 😅 allright fair enough

@altryne since you're looking at the code right now could you remove that line while you're at it?

**Comment by altryne** [comment]
Removed in #229
