### ISSUE TITLE
[BUG?] Textual inversion embedding Runtime error

### ISSUE THREAD

**Issue by grimbit** [hlky/stable-diffusion-webui#199]
I dropped one of the tuned embedding files for textual inversion in to the WebUI and tried running a simple prompt.

Gave a Runtime error (txt2img):
`Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.`

**Comment by hlky** [comment]
You need to run with --no-half and --precision full with textual inversion for now

Closing this because ^ is the solution

Btw, Textual inversion implementation will be overhauled soon, a Discussion about Textual Inversion will be created soon
