### ISSUE TITLE
[FEATURE REQUEST] Create Prompt Matrix option should also create image batches for each prompt

### ISSUE THREAD

**Issue by ZeroCool940711** [hlky/stable-diffusion-webui#205]
**Is your feature request related to a problem? Please describe.**
When using the Create Prompt Matrix option from the advanced tab if you have a prompt that looks like "Fantasy landscape | highly detailed" in will generate a total of 2 iterations/images as that is the number of permutations for that prompt and even if you have the batch count set to something like 5 only 2 images will be created as it completely ignores the batch count.

**Describe the solution you'd like**
When using a batch count higher than 1 it should generate that number of batches for each permutation of the prompt matrix, so, in the example mentioned before it should generate 5 images for each permutation so a total of 10 images should be created. This should make it easier testing different prompts combinations to see how they affect each other and also for creating big batches of images from multiple prompts at once, perfect for leaving it running overnight while you sleep.

**Comment by hlky** [comment]
This could be accomplished from the GUI when #187 is done by just enter the same prompt 5 times.

Wait for #187 and check out [this](https://github.com/hlky/stable-diffusion-webui/blob/master/README.md#prompt-combinations) which might be the kind of combinations you want compared to prompt matrix 

or the --cli batch processing feature, which needs documenting at the moment but is implemented 

Changing the prompt matrix feature itself is too complex when there's a simpler solution
