### ISSUE TITLE
Error on loopback in Img2Img.

### ISSUE THREAD

**Issue by MarcusMcNut** [hlky/stable-diffusion-webui#206]
I tried to setup a batch count of 8 for batches of 3.  I'm using a 512x512 image, and I'm getting the following error.

`einsum(): operands do not broadcast with remapped shapes [original->remapped]: [48, 4096, 40]->[48, 4096, 1, 40] [16, 77, 40]->[16, 1, 77, 40]`  I've tried this multiple times with different sized images and always have the same error.

**Comment by hlky** [comment]
Can't reproduce, must have been fixed.
