### ISSUE TITLE
Separate directories for samples

### ISSUE THREAD

**Issue by JohannesGaessler** [hlky/stable-diffusion-webui#23]
Currently all individual samples are saved to the same directory.
I prefer to sort individual samples by prompt.
With previous scripts I simply hardcoded this in.
Is this functionality desirable to more people than just me?
If yes I will do a proper implementation.

**Comment by palexpereira** [comment]
Yes this is definitely something i would be interested in!

**Comment by JohannesGaessler** [comment]
All right.
I'll adapt my version unless someone else wants to do it.

For guidance:
What should be the default?
(There will be a toggle in the GUI.)
Is there a specific reason prompts get cut off at exactly 128 characters of is this just to ensure a lot of headroom for the more common 255 character limit?
Should I append a hash of the prompt to the directory names to ensure that two different long prompts always end up in different directories or is this unneeded given the CLIP token hard limit?

**Comment by JohannesGaessler** [comment]
Thanks.
Should I interpret this as you being fine with either directory structure as the default?

**Comment by JohannesGaessler** [comment]
Most people are probably GUI users and hashes will be annoying with GUI file managers.
I think I'll just accept that prompts cannot be separated perfectly in some cases.

**Comment by hlky** [comment]
I suppose there's no need for the index, just use the prompt itself, that way any other batches go into the same folder, sorting isnt important for this feature imo

When the option is enabled change the filenames to remove the prompt but keep the other settings, and then there's no issues with max file path, unless you just drop both to like 64 characters, but then it might end up with some longer differing prompts going into the same folder

but just do whatever you think is best and if anyone who uses that features think it should be different that can open an issue
