### ISSUE TITLE
[BUG] the mask position deviates in img2img's tab when the browser zoomed in.

### ISSUE THREAD

**Issue by ShiratoriAoi** [hlky/stable-diffusion-webui#236]
I'm using Google chrome. 
In img2img's tab, the editor view corrupts the aspect ratio when the browser zoomed in. 
When executing img2img in this state, the mask position deviates. 
I don't know if this is a bug, but I report it because I spent a lot of time. 
Thanks for reading.

**Comment by Alphyn-gunner** [comment]
Can confirm. And sometimes it randomly happens even when the browser is at 100% zoom. 
Example:
![image](https://user-images.githubusercontent.com/34932866/187160843-5a4f0305-5c1f-4a0c-809f-99355c2e3706.png)
Browser: Latest Chrome
OS: Win 10
