### ISSUE TITLE
Expose server to LAN

### ISSUE THREAD

**Issue by joshofbass** [hlky/stable-diffusion-webui#24]
At the moment I can figure out how to use it on localhost, and via gradio link by adding share=True. Is there an option to just use my local ip?

**Comment by hlky** [comment]
```
server_name='0.0.0.0'
```

this should already be set and be accessible on your local network, if you cant access it from your local network it would be a firewall issue
try


* search "Windows Defender Firewall with Advanced Security" in start menu
* Inbound rules > New rule > Port > TCP + Specific local ports: <port it's running on>

**Comment by toniohc** [comment]
Must be firewall issue. I can access from my network and outside ( with NAT/PAT rerouting ) without issue.

**Comment by felixbro** [comment]
> ```
> server_name='0.0.0.0'
> ```
> 
> this should already be set and be accessible on your local network, if you cant access it from your local network it would be a firewall issue try
> 
> * search "Windows Defender Firewall with Advanced Security" in start menu
> * Inbound rules > New rule > Port > TCP + Specific local ports: <port it's running on>

Thats exactly what i tried and still cant access my windows pc over lan on my phone or any other device. did someone has a suggestion what else i can check?
