### ISSUE TITLE
[BUG]can not Select image number from results for copying

### ISSUE THREAD

**Issue by liangwei191** [hlky/stable-diffusion-webui#247]
**Describe the bug**
can not Select image number from results for copying

**To Reproduce**
1. Go to i2i tab
2.set the batch count slider and set to more than 1
3.the list generated on right neither can be assigned by select nor can change the number manually(uneditable textbox).(can be selected in old version)

tested on chrome

**Comment by nderscore** [comment]
That textbox was removed. If you update to the latest version of the [main repository](https://github.com/hlky/stable-diffusion), it should be fixed.

**Comment by hlky** [comment]
> That textbox was removed. If you update to the latest version of the [main repository](https://github.com/hlky/stable-diffusion), it should be fixed.

Yeah this issue was already synced, the change for the positioning of the button is synced now too

@liangwei191 reopen if you have any issues
