### ISSUE TITLE
Optimize the memory usage

### ISSUE THREAD

**Issue by aolko** [hlky/stable-diffusion-webui#25]
![image](https://user-images.githubusercontent.com/581458/186702203-d9221865-2d12-4f0c-b395-9f7dd9e58591.png)
I have a gtx 1060 with 6Gb VRAM. Webui claims almost the whole VRAM and keeps crashing when doing either txt2img or img2img:

```
!!Runtime error (img2img)!!
 CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
exiting...calling os._exit(0)
```

Please optimize the memory usage, so the webui is more stable and not crashing the generarion.

( an example of webui with more stable generation would be [basujindal/stable-diffusion](https://github.com/basujindal/stable-diffusion), however the drawback is the lack of advanced features )

**Comment by hlky** [comment]
implement it yourself or buy a new gpu, vramlets are not supported

**Comment by Craftyawesome** [comment]
Make sure you are using batch size 1. And don't use "Fix faces using GFPGAN" and batch count >1 at the same time. That keeps it working on 6GB for me.
