### ISSUE TITLE
[FEATURE REQUEST] - Unfork the repo from AUTOMATIC1111

### ISSUE THREAD

**Issue by altryne** [hlky/stable-diffusion-webui#255]
**Is your feature request related to a problem? Please describe.**
![CleanShot 2022-08-29 at 08 34 46@2x](https://user-images.githubusercontent.com/463317/187227383-3b8dee8e-f127-4a9b-9d9f-9805593810dd.jpg)

Github still thinks we're a fork of the original ,but I don't see a future where we merge with Automatics repo.

Would be cool to "unfork" and it'll remove this notice ⬆️

Can be done like so: 
https://ralphjsmit.com/unfork-github-repo

**Comment by hlky** [comment]
I was wondering how to do this, thanks, just done it, now we wait!

**Comment by hlky** [comment]
Done, thanks GitHub!

**Comment by altryne** [comment]
yay!
