### ISSUE TITLE
[BUG] --save-metadata doesn't seem to work

### ISSUE THREAD

**Issue by Michoko92** [hlky/stable-diffusion-webui#260]
Hi,

If I launch webui.py with the --save--metadata argument, then generate a txt2img PNG image, no data is actually saved to the generated image. I traced the code, and image.save(f"{filename_i}.png", pnginfo=metadata) is called properly. However, when I examine the image with various tools (Windows explorer, Photoshop...), there is no EXIF information in the PNG file.

Thank you!

**Comment by AbdBarho** [comment]
@Michoko92 could you try again here? 
https://www.nayuki.io/page/png-file-chunk-inspector

**Comment by Michoko92** [comment]
Hmm, with this tool, I can indeed see the information, thank you. Isn't there a way to make it more accessible, though? By reading the page you linked, it seems the tool reads some data directly from the PNG file, but doesn't handle EXIF data. So if I understand correctly, the generation information is currently not stored as EXIF data.  I think that storing EXIF data would be much handier, and more accessible.

**Comment by Michoko92** [comment]
I saw this today, and thought it was a very cool idea: https://www.reddit.com/r/StableDiffusion/comments/x1hp4u/my_easytoinstall_windows_gui_for_stable_diffusion/

The guy implemented a, SD GUI where you just have to drop the PNG into the window, and it will retrieve the PNG data. How smart and convenient!
