### ISSUE TITLE
[BUG] ValueError: invalid literal for int() with base 10: '0,1,2'

### ISSUE THREAD

**Issue by ZeroCool940711** [hlky/stable-diffusion-webui#273]
**Describe the bug**
When running the `webui.py` file on Windows and having multiple GPUs with the `CUDA_VISIBLE_DEVICES` variable set on the path, line 28 on the `webui.py` throws a ValueError exception, this is because `os.environ.get('CUDA_VISIBLE_DEVICES', 0)` is returning a list and not an int. To solve it this part in line 28 should be changed to `default=list(os.environ.get('CUDA_VISIBLE_DEVICES', 0))`  so it expects a list instead of an int, with the list it should still work on single GPU devices but can't test it to be 100%.

**Screenshots**
![image](https://user-images.githubusercontent.com/5977640/187268743-53039d2b-1a09-4b67-884b-a6472e9b9319.png)

**Comment by hlky** [comment]
`default=int(os.environ.get('CUDA_VISIBLE_DEVICES', 0)`
i don't know why whoever set this thought it was a good idea, fixed 3fb8e64

**Comment by hlky** [comment]
or if that setting is even needed, going to remove the environment thing all together

**Comment by ZeroCool940711** [comment]
@hlky that wasn't like that before, I remember it was just a `0` there to select the first GPU and that was it.

**Comment by hlky** [comment]
You mean the default or the environment variable code further down? The default was just 0 which is the sensible thing, I don't think they considered multiple gpus

**Comment by hlky** [comment]
I've removed the environment code itself though because I think it might mess with other software
