### ISSUE TITLE
The mask in the img2img is offset

### ISSUE THREAD

**Issue by georgzoeller** [hlky/stable-diffusion-webui#275]
![image](https://user-images.githubusercontent.com/2640999/187270764-488c8cc8-f422-44a1-9726-5f3857ae9cbc.png)

Prompt:
- blue cloudy sky anime
- Steps: 50, Sampler: k_lms, CFG scale: 11.5, Seed: 22, Denoising strength: 0.91
- 768x384 (<--- this is probably the issue)
- Resize setting doesn't matter

**Comment by Goldenkoron** [comment]
Can confirm I also get this issue. It only happens for me with images using aspect ratios that are not 1:1. Further off it is from 1:1 the more offset/distorted it gets. Hoping this gets fixed soon so I can put together some nice 16:9 images.

**Comment by Shark1337** [comment]
if in the browser you do ctl + - and ctl + + it is solved and the mask is calibrated,

this as a temporary solution

**Comment by hlky** [comment]
@Shark1337 this worked for me too, also just switching between crop and mask mode, the editor is a tempremental feature that is the best it can be given the technical limitations of gradio.
