### ISSUE TITLE
Support of Img2Img cropping

### ISSUE THREAD

**Issue by Tohricat** [hlky/stable-diffusion-webui#28]
Hello! Loving the UI so far. Would it be possible to add cropping of the init image before generation as seen in other Gradio stable diffusion UIs?

![image](https://user-images.githubusercontent.com/53372339/186743928-c22a2143-8274-4540-9d8e-1e628bdd6cc3.png)

**Comment by hlky** [comment]
```
gr.Radio(label="Resize mode", choices=["Just resize", "Crop and resize", "Resize and fill"], type="index", value="Just resize"),
```

already a feature, does it not work?

**Comment by Tohricat** [comment]
That feature works! I'm referring to being able to crop the init image to specific size before doing anything with it (as seen in the image)

**Comment by hlky** [comment]
so you want to be able to crop then mask? is this actually a feature in other versions? first thoughts are that this would require 2 image input boxes

**Comment by Tohricat** [comment]
Yeah! It caught me off-guard when using this webgui. It would save a lot of time as at the moment, I need to crop the image in an external editor (if I want an init image of a face but not the body, for example). Is this something that you'd consider?

**Comment by hlky** [comment]
i'll look into it

**Comment by hlky** [comment]
can you link to the repo that has crop and mask on the same Image component?

**Comment by Tohricat** [comment]
Unfortunately there isn't another repo that I know of that can do this - apologies for the confusion in my original suggestion.

**Comment by hlky** [comment]
oh, in that case it will probably require 2 Image components, needs looking into further, thanks for the clarification though

**Comment by hlky** [comment]
#44  implemented this
