### ISSUE TITLE
[BUG] Batch size (how many images are in a batch; memory-hungry) Fails when using 'n' bigger than 1.

### ISSUE THREAD

**Issue by psicopedagoloco** [hlky/stable-diffusion-webui#284]
**Bug description**

I discovered something went wrong when I wanted to create 5 images and it took over 650 seconds. 

![image](https://user-images.githubusercontent.com/112212720/187293188-b9a69016-a246-4faa-bd10-5003b56667fd.png)

After asking on twitter, [Altryne](https://twitter.com/altryne) told me it could have been disconnected, but when I checked a few times, I realized when you set your batch count, it gives you a grid of "n" images, but when you change the batch size, n > 1, it gets stuck. The iteration in the colab shows it was completed, but the WebUI doesn't show the results and get stuck counting the seconds to the infinite. 

![image](https://user-images.githubusercontent.com/112212720/187293793-da9b849e-1bb0-4b3f-b9fd-8b4791d5d3f8.png)
![image](https://user-images.githubusercontent.com/112212720/187293829-0a1d794b-6640-4c3a-a7cb-2d64243e6161.png)
![image](https://user-images.githubusercontent.com/112212720/187293859-aea2985b-cd2f-43de-85d2-4f5d7719d0ef.png)
![image](https://user-images.githubusercontent.com/112212720/187293874-715e219b-58bf-47fe-94a7-816f0116be61.png)

**To Reproduce**
1. Go to your public url gradio.app,
2. Click on 'Stable diffusion text-to-image unified' tab.
3. Write your prompt (example: A simple icecream)
4. Scroll down to 'Batch size (how many images are in a batch; memory-hungry)'
5. Change the n from 1 to 2 or above. 
6. Scroll up to "generate"
7. See error.

**Expected behavior**
You'll see the Stable Diffusion WebUI running and counting the seconds, you can optionally see your Google Colab Notebook running with the last prompt you generated, it will show it's running, until it's done, but if you go back to the WebUI, it will keep counting the seconds for ever. The images will be generated on your Google Drive, but the WebUI will be running forever.

**Screenshots**
![image](https://user-images.githubusercontent.com/112212720/187295318-337a4d83-8bca-42cd-8990-be6067cd91e6.png)
Here you can see a screenshot of a simple prompt trying to generate 4 images, and taking over 386 seconds to do it.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Edge]
 - Version [104.0.1293.70, 64 bits]

**Additional context**
No further context available.

**Comment by hlky** [comment]
You want `batch count` not `batch size`

Read the descriptions next to them :)

`batch count` is how many 'batches' of images to make

`batch size` is how many images are made in a batch, this increases memory usage

If you just want 5 images, you want a `batch count` of 5

**Comment by hlky** [comment]
To clarify, setting batch_size 5 is as the description suggests, memory hungry, it is not crashing due to a bug rather due to running out of vram.
