### ISSUE TITLE
[FEATURE REQUEST] Prompt matrix modifiers not only at the end of prompt

### ISSUE THREAD

**Issue by Nachtrose** [hlky/stable-diffusion-webui#285]
Would it be possible make the prompt matrix in such a way, the you could put the modifier anywhere inside the prompt?
Would probably require some new syntax to bracket off the mod section.

To illustrate what i mean:

Current state:
prompt | mod1 | mod2 -> prompt, prompt mod1, prompt mod2, prompt mod 1 mod2

expected new state:
prompt_part1 (PT1) < mod1 | mod2 | mod 3 > prompt_part2 (PT2) -> PT1 PT2, PT1 mod1 PT2, PT1 mod2 PT2, ...

in this way you could finetune which parts you want to modify ( for example just a color of some part in the middle of the prompt ).
Probably still needs to be limited to one patch of mods, as it would really fast get out of hand.

**Comment by hlky** [comment]
I think [prompt combinations ](https://github.com/hlky/stable-diffusion-webui#prompt-combinations) is more like what you want

**Comment by Nachtrose** [comment]
Hmm... missed that one in the documentation ( no fancy image for it :-) ) . Thinking about it, this would probably solve most of my expected use cases.  At this point at least. The major difference being, prompt combination only iterates trough the array one by one, while in the matrix format it would also combine the values.

Maybe a better example would be the busy street example from the docu. Just you have already a "fine tuned style/batch of artists" which you want use and for some reason, they tend to be put at the end of the prompt. Makes that any sense?

**Comment by hlky** [comment]
I think you're just try to accomplish too much at once, I'm not sure sure exactly what sort of combination you're after that can't be done either prompt matrix, prompt combinations or just changing the prompt and making another batch of images

**Comment by Nachtrose** [comment]
That sounds reasonable...
Ok, i'll leave it at that. Should i run into some real use scenarios, no matter how niche, i'll let you know.

Sorry for bothering you. I'm quite new to all of this and may be lacking some key knowledge here and there.
