### ISSUE TITLE
[BUG] textual-inversion crashes web UI

### ISSUE THREAD

**Issue by kodxana** [hlky/stable-diffusion-webui#286]
**Describe the bug**
```
!!Runtime error (txt2img)!! 
 Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.
 ```

**To Reproduce**
1. Upload embeddings_gs.pt file
2. Create prompt with * in it
3. Press generate

**Desktop (please complete the following information):**
 - OS: [Debian 11]
 - Browser [Brave]
 - Version [1.42.97]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hlky** [comment]
Possible duplicate #80 #53 #199 

textual inversion embeddings are trained at full precision so you need to [run at full precision ](https://github.com/hlky/stable-diffusion-webui/wiki/Command-line-options)

**Comment by kodxana** [comment]
Tried switching web ui to full precision and still that same :/

**Comment by kodxana** [comment]
Some updates:
- Aparently when running in docker full precision needs to be set in entrypoint.sh script
- After enabling full precision it works just in my case OOM error
- Are there any plans for FP16 support?

**Comment by hlky** [comment]
I'll add a note about where to set command line options when using docker.

I think it's possible to enable inference (image generation) on half precision with the full precision embeddings but when I made some changes to the training code to make it half precision I ended up with broken embedding files and black images.

**Comment by hlky** [comment]
@kodxana where are you getting your embeddings from?

**Comment by kodxana** [comment]
I have started training my own custom model two days ago using the colab notebook.

**Comment by kodxana** [comment]
> I'll add a note about where to set command line options when using docker.
> 
> I think it's possible to enable inference (image generation) on half precision with the full precision embeddings but when I made some changes to the training code to make it half precision I ended up with broken embedding files and black images.

Let me know how :D . Wanna test it :)
