### ISSUE TITLE
[BUG] Masking not working

### ISSUE THREAD

**Issue by thedyze** [hlky/stable-diffusion-webui#290]
After masking and selecting the option to keep only the masked area, nothing is inpainted when pressing generate

**Comment by hlky** [comment]
If you mask an area, keep only maksed area, how can anything be 'inpainted' to the masked area? I believe you're just misunderstanding the usage of img2img.

**Comment by hlky** [comment]
The changes in #308 might help do what you want.

**Comment by thedyze** [comment]
> If you mask an area, keep only maksed area, how can anything be 'inpainted' to the masked area? I believe you're just misunderstanding the usage of img2img.

yeah, as I understood it, 'keep only masked area' meant to keep this part of the image, and inpaint the rest.
