### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by liangwei191** [hlky/stable-diffusion-webui#293]
currently some advanced i2i user using crop a square area and add detail to this area then use ps to put it back.
as i2i is not real inpaint and can not describe all the detail things in one prompt.crop and merge is quite neccessary. 
i hope whether there could be a function to simulate this as doing manually can not make coorinates accurately.
It is quite complex I know as it seems require a  secondary interface after choose the image which want to change.So just a suggestion.

**Comment by hlky** [comment]
>It is quite complex

Yes, it is quite a complex process to achieve your desired results, it's not clear exactly what you want to be added that would somehow get the results you want automatically.
