### ISSUE TITLE
[Maintainers] - Should we protect the master branch from pushes? 

### ISSUE THREAD

**Issue by altryne** [hlky/stable-diffusion-webui#295]
Now that there are a few maintainers, should we move to a branch-ed based dev cycle? 
This way we won't be "surprised" by a sudden push on master. 

@hlky thoughts?

**Comment by JoshuaKimsey** [comment]
Given how rapidly things are changing still, maybe it's best to wait for a stable release before we do that? Once a stable release is out, then a branch-based dev cycle is definitely going to be necessary.

**Comment by hlky** [comment]
I don't see why not @altryne
