### ISSUE TITLE
[BUG] Prompt textbox does not revert from multi-line to single-line (Solution provided)

### ISSUE THREAD

**Issue by athu16** [hlky/stable-diffusion-webui#304]
**Describe the bug**
When "Submit on enter?" is switched from "No" to "Yes", the prompt textbox does not revert to single-line mode.

**To Reproduce**
1. Change "Submit on enter" from "Yes" to "No", observe the prompt checkbox change from single-line to multi-line
2. Change "Submit on enter" back to "Yes", observe how the prompt STAYS in multi-line mode.

**Expected behavior**
The prompt textbox should change back to single-line mode

**Solution**
In frontend.py, change line 83 as follows:
From
![image](https://user-images.githubusercontent.com/93036639/187377299-f02e47dd-189e-4f54-a67e-9289a23d01b1.png)
To
![image](https://user-images.githubusercontent.com/93036639/187377377-27fcf35f-7b1f-4898-adbf-9c444a321275.png)
I would have done it myself, but I can't figure out how to make a pull request

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 104.0

**Comment by hlky** [comment]
thanks, you'll need to wait for the changes to be synced to main repo unless you understand how to update from dev repo -> main repo yourself

```
Dev repo is set up to be easy for developers so the structure is different.
Changes are synced to main repo.
GitHub Actions puts things in the right places.
If you can't tell where things go check .github/sync.yml
```
