### ISSUE TITLE
[BUG] img2img list index out of range

### ISSUE THREAD

**Issue by HenkDz** [hlky/stable-diffusion-webui#313]
**Describe the bug**
The last update introduced a bug. You can't use mask or uncrop.

**To Reproduce**
After using txt2img I push the image to img2img. If I change any option, like mask or uncrop I get the error "list index out of range"

**Screenshots**
![image](https://user-images.githubusercontent.com/17301927/187430109-8d141763-d0ff-4fee-abc9-54fa900a2146.png)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [e.g. 104]
 - GPU: RTX 3090
 - RAM: 32 GB
 - CPU: Ryzen 5950

**Comment by HenkDz** [comment]
If I try to use existing pulled image from txt2img without trying to mask or uncrop I get another error

![image](https://user-images.githubusercontent.com/17301927/187431326-77aed290-0d4c-4ce7-b6f2-711ccf556e4e.png)

**Comment by hlky** [comment]
>After using txt2img I push the image to img2img. If I change any option, like mask or uncrop I get the error "list index out of range"

This is working for me.

**Comment by athu16** [comment]
Can confirm, I have the same issue as well. Clicking "Generate" generates another error message.
Changing Image Editor Mode
`Traceback (most recent call last):
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 594, in postprocess_data
    prediction_value = predictions[i]
IndexError: list index out of range`
Pressing "Generate":
`Traceback (most recent call last):
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\*****\Apps\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1120, in img2img
    init_img = init_info["image"]
TypeError: 'Image' object is not subscriptable`

**Comment by HenkDz** [comment]
@athu16 
![image](https://user-images.githubusercontent.com/17301927/187435850-0485a435-0a97-4244-9256-27251367806a.png)

**Comment by eva9900** [comment]
https://github.com/hlky/stable-diffusion-webui/commit/fe6f1e3dc5773aabf879e1d686699092bf483a6b

**Comment by hlky** [comment]
@eva9900 ?

@HenkDz @athu16 I don't know what issue you are having, you haven't given enough information, and it has been stated many times that the image editor, txt2img result to img2img etc are experimental - quite literally pushing the limits of what Gradio can actually do, extremely temperamental, and don't do anything you can't just do yourself.
There are 3 other people working on the image editor, I am trying to merge everyone's changes to it together, but as I've said this is all highly experimental, and it's getting beyond the scope of this project, and quite frankly a bit ridiculous, this project is not an image editor, this project is a webui for stable diffusion, please just use stable diffusion for what it is, if you need to crop an init image you can easily do it before you upload it, if you need to mask you will get far better results doing it yourself in photoshop.

**Comment by HenkDz** [comment]
@hlky issue happens with uploading my own images as well. It's not strictly related to the pushing from txt2img it's rather the whole img2img tab issue.

**Comment by oobabooga** [comment]
I can confirm, img2img is not working for me. I also can't draw masks (the brush doesn't appear).

**Comment by athu16** [comment]
@HenkDz @oobabooga @throwaway-mezzo-mix Guys the masking is working properly for me after the latest commit. Could you guys check on your end?

**Comment by codedealer** [comment]
Just check out master and tested img2img. Works as expected. That being said I think there were changed to the main repo https://github.com/hlky/stable-diffusion that I haven't pulled yet. Maybe the breakage is there?

**Comment by hlky** [comment]
@codedealer maybe something didn't get synced properly, what's the difference between this repo and the main repo?

**Comment by throwaway-mezzo-mix** [comment]
@athu16 After updating to the latest commit switching between modes doesn't immediately cause an error and masking seems to work, however trying to generate (on either txt2img or img2img) threw this error for me:
`!!Runtime error (img2img)!!
 Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
 The only option i'm running it with is --optimized.

**Comment by codedealer** [comment]
@hlky 
Well at a first glance I can tell you right away I don't have [this commit currently](https://github.com/hlky/stable-diffusion/commit/84e7a0b8e064cba86e4e3155bc9e216e967d16df)

**Comment by ZeroCool940711** [comment]
@hlky I might be wrong but I think some of the changes from the frontend folder are not been synced correctly between this repo and the main repo, I had to manually download the new files that were changed there a couple of hours ago because I was missing some CSS and I did a git pull and nothing new was downloaded, only after I manually downloaded the frontend folder I was able to run the code again.

**Comment by hlky** [comment]
@ZeroCool940711 everything appears to be synced properly, i did notice an error in the css

**Comment by hlky** [comment]
@codedealer that was supposed to add ddim support for the new masking thing, ill try reverting it on my end and see if that fixes anything

**Comment by ZeroCool940711** [comment]
It might be synced properly now because there have been a few commits since I last did a git pull, the last time I did a git pull was 4 hours ago and back then it wasn't properly synced or maybe it was that some files were not added correctly to be tracked by git and they were not uploaded.

**Comment by codedealer** [comment]
[@ZeroCool](https://github.com/ZeroCool940711) the latest changes to the frontend are only an hour old, it might be possible you pulled in the middle of the merges? It looks good currently.

**Comment by ZeroCool940711** [comment]
> it might be possible you pulled in the middle of the merges

Yeah, that might have been possible.

**Comment by athu16** [comment]
![image](https://user-images.githubusercontent.com/93036639/187469920-112cd597-540e-44af-930a-bad6bb4943a4.png)
@hlky is this supposed to be like this? These are the only parameters different between the functions that run after clicking "generate" and pressing ENTER on the prompt.

Pressing "Generate" works normally but pressing ENTER inside the prompt box gives
`TypeError: 'Image' object is not subscriptable`

**Comment by codedealer** [comment]
Ah. I got it
![image](https://user-images.githubusercontent.com/4258136/187472290-02fb8b99-820a-46a3-a5d1-e7a2fbecf011.png)
To reproduce:
1. Go to img2img
2. Put image into mask mode (I also drew on it)
3. Enter prompt
4. **Hit Enter**

**Comment by hlky** [comment]
https://user-images.githubusercontent.com/106811348/187473184-e6411a59-ba21-40d3-9256-b1a043fc41a1.mp4

**Comment by codedealer** [comment]
I said hit enter, my friend. There **is** a difference

**Comment by hlky** [comment]
@codedealer do we really need to be able to hit enter? unless someone can track down why this is happening I think people should just click generate

**Comment by codedealer** [comment]
I mean, changing the argument seem to have done the trick?
New line 283 in [frontend.py](https://github.com/hlky/stable-diffusion/blob/2cb47b6a2ca64c08d1e0b6734a234cc57f37b23c/frontend/frontend.py#L283)
`[img2img_prompt, img2img_image_editor_mode, img2img_image_mask, img2img_mask,`
