### ISSUE TITLE
[FEATURE REQUEST] Batch Processing Queue - Ability to perform tasks one after the other according to pre-selected settings

### ISSUE THREAD

**Issue by search620** [hlky/stable-diffusion-webui#314]
Ability to perform tasks one after the other according to pre-selected settings.

I find myself every time waiting for the generation to finish in order to re-execute with the same settings only with a different model or different parameters. 

It would be very nice if it was possible to do it by "Batch Processing Queue" of the setting\models\prompts\sliders in fact everything at Queue. 

such a feature would save precious time for the user instead of working manually.
In addition to that, it would be nice if there was presets that can be saved and applied when needed (absolutely necessary)

Thank you very much love you all :)

**Comment by hlky** [comment]
This is possible atm with the --cli option and the appropriate configuration file. Adding to a queue in the GUI would be an excellent feature though.

**Comment by thedyze** [comment]
a queue for img2img would be really nice!

**Comment by search620** [comment]
> This is possible atm with the --cli option, the appropriate configuration file, and some scripting. Adding to a queue in the GUI would be an excellent feature though.

I am like that you like it ❤I don't know what cli is but I will ask

**Comment by hlky** [comment]
Duplicate #326
