### ISSUE TITLE
[BUG] SD creates empty folders for each combination of 'prompt matrix' keywords even though 'save individual files' and 'write sample info files' are disabled.

### ISSUE THREAD

**Issue by igoralvarezz** [hlky/stable-diffusion-webui#317]
I'm exploring txt2img prompt combination with the 'Create prompt matrix' option and I'm mostly interested only on the final grid file and the seed to reproduce a result if I like it. With that in mind, and in order to reduce unnecessary disk usage, I unchecked the 'Save Individual images' and 'write sample info files' options but SD in creating one empty folder for each prompt tried still.

**To Reproduce**
1. Go to txt2img and insert a prompt with the keywords separated by pipes '|' (I used 9 different keywords)
2. Activate the 'Advanced' options tab and check 'Create Prompt Matrix', 'Save Grid' and 'Sort Samples by prompt'
3. Uncheck 'Save individual images' and 'Write sample info files' and generate. SD will create empty folders for each combination

**Expected behavior**
I think that if SD is not creating individual images neither info files for each combination, the folder with each prompt in its name should not be created.

**Desktop (please complete the following information):**
 - OS: [Google Colab Notebook](https://colab.research.google.com/github/altryne/sd-webui-colab/blob/main/Stable_Diffusion_WebUi_Altryne.ipynb) linked in the README
 - Google Chrome Version 102.0.5005.115 (Official Build) (64-bit) on Debian 11

**Additional context**
Not sure if this repo issues applies to the Colab Notebook version, but as it is listed on the Readme and it doesn't seem to be a Bug related to the Colab environment itself, I'm posting anyway. Apologies if that's not the case.

**Comment by igoralvarezz** [comment]
Hm, sorry if it is somehow a dumb question but:
I initially though that the 'sort samples by prompt' had to do with the order the images were rendered in case of 'prompt matrix' grid images (less words and start of the phrase first). Is it the option responsible to create a folder by each prompt of the run?

**Comment by hlky** [comment]
Sort samples by prompt is for the individual samples:

> with the prompt `a corgi wearing a top hat as an oil painting`[1] and the 'sort samples by prompt' option the images are saved in a subfolder of the samples folder[2]  named `a corgi wearing a top hat as an oil painting`[3] 
> every time you use the same prompt[4] the new images are saved to the same folder
[1] the default for txt2img 
[2] of either txt2img or img2img
[3] it will get truncated to 128 characters to avoid path limit issues
[4] on the same mode
