### ISSUE TITLE
[BUG] Prompt Matrix final grid image not rendering label text correctly

### ISSUE THREAD

**Issue by igoralvarezz** [hlky/stable-diffusion-webui#318]
**Describe the bug**
Final grid image with 'prompt matrix' option not rendering the text correctly.
I noticed two bugs:
1. Strike-through font not rendering correctly (shows each letter of the word separated by □)
2. If there are a lot of different terms in the matrix, the stacking of them leave some words out of the image boundaries

**To Reproduce**
1. Generate a prompt matrix image with 8 or more terms, I've used "a large black object|flying through a purple sky|a digital rendering by Chris Moore|cg society|precisionism|ue5|playstation 5 screenshot|concept art"
2. The final grid image will have problems rendering the strike-through text. 

**Expected behavior**
1.Strikethrough rendering correctly.
2.More white margin around the images to allow for all the terms in the prompt matrix to show on final image.

**Screenshots**
![image](https://user-images.githubusercontent.com/84546224/187453564-acd7d3cd-4077-4c0e-b0b8-99299aefeb34.png)

**Running on Desktop:**
 - OS: [Google Colab Notebook ](https://colab.research.google.com/github/altryne/sd-webui-colab/blob/main/Stable_Diffusion_WebUi_Altryne.ipynb) linked in the README
 - Google Chrome Version 102.0.5005.115 (Official Build) (64-bit) on Debian 11

**Additional context**
I know it may be kind of an edge case for the quantity of terms but the strikethrough I guess will be an issue to everyone running the Colab notebook if the issue is reproducible.

**Comment by hlky** [comment]
The first issue might be something to do with the font the colab is loading 

The second is could be related, or like you said it just needs a bigger margin

**Comment by vibrantrida** [comment]
For the first issue, is the strikethrough really necessary? I think being gray suffices to denote that the prompt is inactive.

**Comment by hlky** [comment]
@vibrantrida the original issue author never got back to me, presumably their issue resolved at some point. Other users have had issues that involve colab and fonts not loading/not working.

**Comment by igoralvarezz** [comment]
@hlky Sorry for not getting back earlier. But unfortunately I wasn't able to solve it. But I agree with @vibrantrida , I guess that the font greyed out or even take off the word entirely would be better. 
The second option would even help with the margin problem, saving space (at least for the first items). 
About the margin problem, maybe if we start to draw the final image from the fonts, align them to the left and, after all the rows and collumns are placed, place the images aside with some padding may help adjust the space according to the need of each grid instead of having a fixed margin.

**Comment by vibrantrida** [comment]
> @vibrantrida the original issue author never got back to me, presumably their issue resolved at some point. Other users have had issues that involve colab and fonts not loading/not working.

Why was this closed? The overflowing prompt list is a bigger issue than the strikethrough not rendering correctly.
