### ISSUE TITLE
Loopback should have the option to randomize seed

### ISSUE THREAD

**Issue by jd-3d** [hlky/stable-diffusion-webui#32]
Loopback would be way more useful if it also randomized the seed on each loop (or incremented the seed). When it is stuck on the same seed the image will rapidly degrade. Adding this option would be very useful.

**Comment by hlky** [comment]
can you post an example image to show what you mean by rapidly degrade?
i think loopback was implemented with same seed deliberately and i'm not sure what the result of random seed for each loop would be  
typically the 'loopback' process is done manually anyway

```
Usually, when doing this, you would choose one of many images for the next iteration yourself, so the usefulness of this feature may be questionable, 
```

**Comment by hlky** [comment]
Checked the code, seed is already actually incrementing by 1 each loop, I can make it random but I still don't think the output will be what you're expecting

**Comment by hlky** [comment]
[test this](https://github.com/hlky/stable-diffusion-webui/tree/32-loopback-should-have-the-option-to-randomize-seed)

should work i'm running embedding training so can't test atm

**Comment by jd-3d** [comment]
Thanks for the quick reply. My idea was to use the loopback feature to morph one image into another (say Obama to Trump) over say 20-50 loops/images. This would make for a really interesting animation without needing fake morphs. I'm using a small denoise value (0.3). Here is an example of the degrading (look at the bottom pictures):
https://imgur.com/a/AgzSFTe

I was thinking a random seed might help it from degrading, but I'm actually not sure where the degradation is coming from. I'm still experimenting with other settings.

**Comment by hlky** [comment]
> https://imgur.com/a/AgzSFTe
oh, yeah ive seen something similar someone posted, fix is above, test it, if it stops images degrading ill merge

> loopback feature to morph one image into another (say Obama to Trump) over say 20-50 loops/images. This would make for a really interesting animation without needing fake morphs
nice idea, hopefully it works, i have no idea if it will though

**Comment by jd-3d** [comment]
I tried the fix above, but when the 'Random Loopback Seed' option is checked it uses the identical seed for all loops (which makes things much worse). I'm not a python expert but it may be because in that loop seed_to_int(seed) is not re-evaluated so it always returns the same value.

**Comment by hlky** [comment]
🐸  should have been `seed_to_int(None)`
try again now

**Comment by jd-3d** [comment]
Thanks, it randomizes now. Unfortunately it doesn't fix the image degradation so my idea was wrong. Probably not worth cluttering up the UI with that option. I'll continue to test why the degradation happens and see if any settings help.

**Comment by hlky** [comment]
does it result in anything different at all? if not i won't bother merging for now

**Comment by jd-3d** [comment]
It's different, but due to the random nature sometimes it looks better, sometimes worse. Maybe some might find it useful. But both methods (incrementing and random) suffer from the image gradually degrading. It's like cloning a clone over and over again. Haven't been able to find any settings to combat this.

**Comment by jd-3d** [comment]
Just to finish this off, I was able to get some decent results by limiting the number of loops to around 10 plus some manual selection. Animated gif here: https://www.reddit.com/r/StableDiffusion/comments/wxt6h9/obama_to_trump_using_new_img2img_loopback_feature/
