### ISSUE TITLE
[BUG] Unable to  import the frontend module at startup webui.py

### ISSUE THREAD

**Issue by elter-tef** [hlky/stable-diffusion-webui#322]
I install the webui according to the [guide](https://github.com/hlky/stable-diffusion/wiki/Linux-Installation) with one difference. I have little space in the home directory, so I build in another partition. I use export HOME='other_directory' in order to create an conda environment in this partition. Everything is installed successfully, but when I run linux-setup.sh, I get the following error:
```
Traceback (most recent call last):
  File "~/stabl diffusion/stable diffusion/ultimate-stable-diffusion/scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
ModuleNotFoundError: No module named 'frontend'
Relauncher: Process is ending. Relaunching in 0.5s...
```

**Comment by Notaner** [comment]
I have similar problem with Windows 10, except I am installing via Webui, and on the drive C.

**Comment by altryne** [comment]
I think this issue is out of the scope of this repo, where is this `linux-setup.sh` from? Please see if they can help.

**Comment by wolfsprite** [comment]
> I think this issue is out of the scope of this repo, where is this `linux-setup.sh` from? Please see if they can help.

It's linked to in the Linux guide section of this repo.
https://github.com/sd-webui/stable-diffusion-webui/wiki/Linux-Automated-Setup-Guide#initial-start-guide
