### ISSUE TITLE
[BUG] Performance Regression for Web UI when upscaling images with batch count > 10

### ISSUE THREAD

**Issue by Flux159** [hlky/stable-diffusion-webui#330]
Hi, thanks for all the hard work getting this working - it's super simple to setup and get started generating images. I wanted to point out a perf regression that I noticed between 2 days ago and today when generating a batch of upscaled images from the txt2img UI. This might just be a "wont fix" since it’s kind of an edge case, but wanted to point it out nonetheless.

**Describe the bug**
Previously, when setting the RealESRGAN scaling option, the images sent back to the UI were the unscaled versions. For a batch count of 16 this was fine since the grid & the images could be sent to the browser client relatively quickly. 

I believe that the fixes for #287 (maybe https://github.com/hlky/stable-diffusion-webui/commit/49e6178fd82ca736f9bbc621c6b12487c300e493) started sending the upscaled images to the client instead. This is fine for low batch counts & does the correct thing for users expecting the upscaled images to appear in the UI. 

However, as you increase the number of images created, the amount of data sent increases significantly and slows down the UI due to the large images.

**To Reproduce**
1. Open up the UI at localhost:7860 
2. With the Text to Image Unified tab open, change batch count to 16. Keep batch size at 1.
3. In Advanced settings, check "Upscale images using RealESRGAN". Keep the default of using the x4 plus model.
4. Input any prompt and click generate.
5. Check command log and you will see that once outputs are finished, the UI doesn't update for a while (this seems due to data being sent to the browser - easier to see if running UI from separate computer on network). Eventually the UI grid will update, but clicking on the images may be laggy. 
6. Continue generating images and the tab will slow down / potentially crash.

**Expected behavior**
Larger batches of images (n_iter) should not lag / crash the UI even if using upscaling option.

**Additional context**
Checking the Chrome console it seems like some images are being sent as base64 encoded in JSON back to the client, then rendered in the image grid - it would make sense that this is slower for the larger scaled image sizes (and the grid image is larger as well).

I made a hacky fix on a local branch by just adding the following before appending to the output_images array (for esr & gfpgan images):
```
if (n_iter < 5):
    output_images.append(esrgan_image)
```

Then adding the following before creating the grid):
```
if (n_iter >= 5):
    output_images.append(image)
```

This shows the results in the image grid fairly quickly and keeps the UI responsive (but only the non-upscaled images, so downloading from the webui won't download the upscaled images). Since the grid code also uses the output_images array, the grid generated will also not use the upscaled images.

This is also a really bad temporary hack (& doesn't explain to users that the images in the UI won't be the upscaled images, those are still only saved on the machine running the web ui server), so I wouldn't recommend it as a permanent fix.

**Comment by hlky** [comment]
I knew some issue would arise from it tbh. 

I think the best solution would be to separate the generation and the upscaling but with a queue, so it generates the images and originals show easily in the gallery, but if the esrgan or gfpgan option are enabled the generated images are sent to a queue in the esrgan/gfpgan tab to be upscaled or fixed.

That way post-processing can still be done on generation, it should reduce vram spikes some users get with esrgan/gfpgan, it keeps Gradio Gallery happy (#347 related?) and would also enable batch esrgan/gfpgan on already generated images.

Also, @altryne is this something Gradio can look at re: `images are being sent as base64 encoded in JSON back to the client`, can Gallery use images from the files?

**Comment by AbdBarho** [comment]
@hlky I an mot altryne but I have looked for it extensively with no luck.

Probably because Gradio uses websockets under the hood to transfer most of its stuff, and it does not run a static server that hosts the generated files.

**Comment by ilikenwf** [comment]
If we were using a full fledged webserver like lighty, nginx, or apache, it could handle the image load/unloads with lazy loads from the webserver itself, or a python listener to handle doing that and that alone, just injecting <img> objects into the browser, adding/removing as required.

If we assume we always will load unscaled images, perhaps only even load the upscales if you click a button or double click the image while viewing in gallery?
