### ISSUE TITLE
[FEATURE REQUEST] Allow the user to drag an output .yaml file into the interface to replicate the settings in the file

### ISSUE THREAD

**Issue by lendrick** [hlky/stable-diffusion-webui#335]
It would be nice to be able to use the generated yaml files that go along with the interface to recreate the same settings automatically by dragging them into the interface.

**Comment by codedealer** [comment]
My opinion on that from [prompt history discussion](https://github.com/hlky/stable-diffusion-webui/discussions/216#discussioncomment-3509676)
> More interesting idea that captures me is restoring state from the generated image. There is already an option to store (some?) data in the png_info. If you can drop that image into a gradio app and basically restore the state where you're left off that would be neat I think.

> P.S. I know there are also yaml files but those require another interface to drop and parse them and they are dependent on the image they were generated along with. Why bother when you can pack all the necessary state inside an image?

**Comment by hlky** [comment]
![image](https://user-images.githubusercontent.com/106811348/187684701-777f4118-34a4-448d-9917-cd6b177d2cbd.png)
