### ISSUE TITLE
Nvidia 1660ti green screens

### ISSUE THREAD

**Issue by Tiiberium** [hlky/stable-diffusion-webui#34]
Still looking for a fix for gtx16** series. The problem is, that it doesn't matter what settings i use, i'm always get a green picture instead of the result. 
And it happens only if i use web version, if i generate pictures via cmd, i use in the end of command "--precision full" and everything works fine i got the pictures. 
If i try to run webui.py with --precision full, i have an error "expected scalar type Half but found Float".
Is it possible to fix this bug and use the web version with gtx16**
It's not a big problem, because i can generate pistures with cmd, but with web it would be a little more convenient :)
![grid-00060-1153684867_little_orange_cat](https://user-images.githubusercontent.com/86314993/186765695-58d9b279-5116-4bf1-af2d-98a025e6b11d.jpg)

**Comment by hlky** [comment]
vramlets need not apply

**Comment by kittyinc** [comment]
@Tiiberium I have a 1660 super, try with these flags:
--precission full --no-half flags

**Comment by emeraldminer299** [comment]
@kittyinc I'm not really good with python and other things. What file would I put these arguments in?

**Comment by hlky** [comment]
https://sd-webui.github.io/stable-diffusion-webui/docs/3.cli.html

**Comment by emeraldminer299** [comment]
Thanks for helping my brainlet little self.
