### ISSUE TITLE
[BUG] Textual Inversion Example Embeddings Throw Error

### ISSUE THREAD

**Issue by seandearnaley** [hlky/stable-diffusion-webui#341]
**Describe the bug**
I have been attempting to try the example embeddings anya and tomoko, I have enabled the embeddings in the webui and select the pt files for upload but the server throws an error and exits

**To Reproduce**
1. get example embeddings
2. enable textual inversion in sd
3. open web ui
4. select anya or tomoko example pt files in embeddings box
5. enter any prompt hit enter
6. observe console error

```
!!Runtime error (txt2img)!!
 Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.
exiting...calling os._exit(0)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by Oceanswave** [comment]
try running with --no-half --precision=full

**Comment by hlky** [comment]
Full precision only for now.

Textual inversion is going to be a major feature soon!
