### ISSUE TITLE
inpainting - DDIMsampling ,  unexpected argument z_mask [BUG]

### ISSUE THREAD

**Issue by 1blackbar** [hlky/stable-diffusion-webui#348]
**Describe the bug**
ddim doesnt work with inpainting using mask on newest version
**To Reproduce**
make mask, prompt it and generate result , you get error about z_mask
it works fine in other sampling modes 
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hlky** [comment]
DDIM sampling with img2img required a change in the main repo, it looks like you didn't get the changes from there and just updated from dev.

Reopen if you have issues, thanks.

**Comment by Mikuz** [comment]
I have this same problem
