### ISSUE TITLE
Multi-GPU Problem

### ISSUE THREAD

**Issue by CamelKing1997** [hlky/stable-diffusion-webui#351]
Great Job, thank you!

I have 3090*4 in a linux server，and I have follow the guide with this script https://github.com/JoshuaKimsey/Linux-StableDiffusion-Script/blob/main/linux-sd.sh to succesful run webui with --gpu 0.
But could I run stable diffusion on both 4 gpus?

**Comment by hlky** [comment]
Of course, that's what the --gpu option is for, just run 4 copies of the script. Assuming you mean to generate more images, because you didn't actually specify what you want to do with multiple gpus.
