### ISSUE TITLE
[BUG] The "Save individual images" doesn't seem to work.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [hlky/stable-diffusion-webui#354]
I just updated today and have found that selecting the "Save individual images" check box doesn't seem to do anything now. I am using GFPGAN while creating the batch, but always end up with the two images, whether the "Save individual images" is selected or not.

**Expected behavior**
Deselecting the "Save individual images" check box should only save the end result image, not the original and any modified images as well.

![image](https://user-images.githubusercontent.com/52193044/187612749-1f241216-0d7d-4bb1-8b9f-30248f7fd239.png)

**Desktop (please complete the following information):**
Windows 11

**Comment by search620** [comment]
I agree that this sector should be improved as like:

1. Do not save image
2. Save an image as regular without filters
3. Save image with filters marked (check box)

also split the filter\addons on the same tab into two sectors. one is for the "save\don't save" options and the other sector is for the filter\addon when you choose to check or leave it blank

Something like that will make more sense

**Comment by hlky** [comment]
I don't see why you wouldn't want to keep the original.

**Comment by GalaxyTimeMachine** [comment]
@hlky I often don't want the distorted original, which is why I select GFPGAN. It just increases the amount of files on the drive.

The point is, this did work as expected, until I updated today.

**Comment by search620** [comment]
> I don't see why you wouldn't want to keep the original.

Well sure to save the original this is what I said. 
1 . Do not save the image (if you just want to do post-processing)
2. Save an image as original - without filters
3. Save image with filters - marked in (check box)

If something is unclear please note me. thanks!

**Comment by hlky** [comment]
Should now work how you intend it to, and not how someone else wants it.

**Comment by GalaxyTimeMachine** [comment]
This "fix" is even more broken than before. If you deselect the "Save individual images" check box, the image isn't saved, and it's also not displayed in the UI. A totally pointless option.
Selecting it does only save the final output (in this case after GFPGAN), whereas I'd expect selecting it to save individual files from before and after. Is there a documented behaviour somewhere?

**Comment by hlky** [comment]
`If you deselect both the "Save individual images" and GFPGAN check boxes, the image isn't saved, and it's also not displayed in the UI`

What did you expect to happen when you turn OFF save individual samples and don't use any post-processors? Nothing can be displayed when there's no output.

>whereas I'd expect selecting it to save individual files from before and after.

Leave save individual images on, use the post processor, both images save.

**Comment by hlky** [comment]
So you don't want esrgan applied to gfpgan? If you only want gfpgan tick only gfpgan, if you only want esrgan tick only esrgan, if you want esrgan applied to gfpgan tick both.

>Not having any post processors should just ignore the save individual files option and create a single file anyway.
Why? the option is there for a reason.

**Comment by GalaxyTimeMachine** [comment]
The option should only be there for the case where multiple files would be created but you only want one. This only happens when using post processing, 1 file is created for each of the steps involved (so you end up with three files for one image). The "Save individual files" should be be used when you want to keep all of the iterations of the same image, but disabled when you only want a single file output, the one after post processing has been completed.

**Comment by GalaxyTimeMachine** [comment]
I'm trying to think of ways to explain this better...hopefully this help.

I think of individual files as:
1. An individual file for the original image (the default you should get if nothing or even "Save individual images" is selected).
2. An individual file for the GFPGAN image.
3. An individual file for the ESRGAN file.

If I select GFPGAN and ESRGAN and select "Save individual images", I'd expect all of the above individual images to be saved (3 of them per image generated).
If I select GFPGAN and ESRGAN and de-select "Save individual images", I'd expect all of the above individual steps to run but only the final processed image to be saved (1 image that is a combination of the original > GFPGAN > ESRGAN).

I think, as a minimum, the original image should be saved when nothing is selected. If anyone wants an option to never save anything to disk, then perhaps a new option should be added for that.

**Comment by GalaxyTimeMachine** [comment]
@hlky Please re-open this as I consider the changes a backward step from how it previously worked.
