### ISSUE TITLE
[BUG] MemorError over and over

### ISSUE THREAD

**Issue by HenkDz** [hlky/stable-diffusion-webui#359]
**Describe the bug**
I always encounter memory error although I've got an RTX3090 with 24GB VRAM

**To Reproduce**
sometimes when I try to generate 832x832 and sometimes as low as 576x576

**Screenshots**
![image](https://user-images.githubusercontent.com/17301927/187654605-9d41f304-ca9d-449d-9602-7e02ad675ec1.png)

**Desktop (please complete the following information):**
 - OS: win10 RTX3090
 - Browser [ chrome]
 - Version [e.g. 102]

**Additional context**
When this issue appears, I can't restart the webui and can't even play a video game but when I check GPU memory I see it's free for the most part.

**Comment by hlky** [comment]
`memory error` to me suggests its a hardware issue with your graphics card, I don't think it's something I can fix, sorry
