### ISSUE TITLE
img2img 3 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by TristanMorelle** [hlky/stable-diffusion-webui#362]
when uncropping an image (scroll out and crop + fill)

!!Runtime error (img2img)!!
 Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 512, 512] to have 3 channels, but got 4 channels instead
exiting...calling os._exit(0)

**Comment by codedealer** [comment]
Yesterday the type was changed from RGD to RGBA in some places. Likely culprit.

**Comment by hlky** [comment]
I've tried changing it back, doesn't fix, problem must be somewhere else. I don't have time for this and the 'crop and resize' and 'crop and fill' options are pointless, this isn't an image editor and there are technical limitations with gradio that are literally being worked on by gradio for us.

**Comment by TristanMorelle** [comment]
imo the uncrop feature is quite essential for finalizing the image  as 90% of all images are cropping the main feature somehow. Thanks for the attempts
