### ISSUE TITLE
[FEATURE REQUEST] frame interpolation

### ISSUE THREAD

**Issue by AK391** [hlky/stable-diffusion-webui#363]
a use case for interpolation could be animation like this demo https://replicate.com/andreasjansson/stable-diffusion-animation, using https://github.com/google-research/frame-interpolation, would be cool to have a separate tab to support this

**Comment by hlky** [comment]
![image](https://user-images.githubusercontent.com/106811348/187684668-52f98447-05c8-41cf-b8ec-2b88d9a4c227.png)
