### ISSUE TITLE
[FEATURE REQUEST] Show the seed of a selected image + Add index of Iteration on the grid + more... |Details inside photos are attached|

### ISSUE THREAD

**Issue by search620** [hlky/stable-diffusion-webui#364]
![2022-08-31_14-41-24](https://user-images.githubusercontent.com/56544202/187677137-b38b4252-f8bd-4a74-bc70-3d77ec3e5c16.png)

So what do you think about it?

**Comment by hlky** [comment]
![image](https://user-images.githubusercontent.com/106811348/187684617-da8f368d-c7a5-47b8-9547-16a9e04a3c7a.png)
