### ISSUE TITLE
[BUG] Interface forgets everything on refresh or going forward back

### ISSUE THREAD

**Issue by TiagoTiago** [hlky/stable-diffusion-webui#375]
**Describe the bug**
If you hit refresh, or navigates away (for example, by accidentally dropping the image file outside of the image area making the browser navigate to the image itself) and then go back, all the parameters, loaded image etc are reset to the default.

**Expected behavior**
Everything should be remembered until the tab itself is closed, even if you go to a different address and then hits back; like how many text boxes and such behave on many sites. Or at the very least, have the "are you sure you wanna leave this page?" warning enabled to avoid accidentally leaving.

**Comment by altryne** [comment]
since the proposed maintanace is to move feature requests to discussions, please move this into the discussions so folks can upvote.

This isn't a bug by definition, as this is how the system was built, there's no way to store settings cached in a browser session in gradio.
