### ISSUE TITLE
[MAINTENANCE] Edit issue templates to direct feature requests to the discussion panel 

### ISSUE THREAD

**Issue by codedealer** [hlky/stable-diffusion-webui#382]
Currently there's a feat request template available which encourages people to post in issues. Either remove it or modify it to state clearly that this is not a place to post.

There is an option to put a link to the discussions page in config.yaml I believe?

**Comment by altryne** [comment]
Could be a good way to clean out issues and also get the insight of the community of what they want to focus on next. 
@codedealer mind adding a quick pr for this? 🙏

**Comment by codedealer** [comment]
err? You have to go through the github interface, the old method of editing .github/ISSUE_TEMPLATE folder doesn't work anymore (*I think*). 

Better that someone with access does it as github gods intended.

**Comment by hlky** [comment]
#395
