### ISSUE TITLE
[BUG] "Save Individual Images" doesn't toggle actual settings

### ISSUE THREAD

**Issue by IASB13** [hlky/stable-diffusion-webui#397]
What it says on the tin. Used to work until a memory crash from experimenting with sizes, not it only saves the grid image. I'm assuming there's a command to override it, but I thought I'd let you know. 

Thanks! The UI works great otherwise!

**Comment by IASB13** [comment]
... Currently doubting my own memory, that setting is supposed to put the individual images in the "txt2img-samples" file right? At the moment they ARE being saved in the samples folder under the specific folder for the prompt, but not the other location, and the setting doesn't seem tp change any behavior.

**Comment by hlky** [comment]
> under the specific folder for the prompt

![image](https://user-images.githubusercontent.com/106811348/187903454-d91f12b8-09b3-4cd8-9ed5-1854d96cb692.png)

You must have "Sort samples by prompt" enabled

"Save individual images" should work

**Comment by GalaxyTimeMachine** [comment]
It doesn't work. It saves the same files, with or without "Save Individual Images" toggled. See #354

**Comment by GalaxyTimeMachine** [comment]
Is it supposed to mean "Save Individual Images" {...for each step of the process}? That's the way it used to work.
The way it works now is to "Save a single post-processed image", which also appears to be the default when it isn't selected and processing is.

**Comment by GalaxyTimeMachine** [comment]
Sorry, but that's a terrible decision to remove the options. It now adds additional steps and time to get the same result.
