### ISSUE TITLE
launch() share with auth fails with an error

### ISSUE THREAD

**Issue by Tom-the-moose** [hlky/stable-diffusion-webui#41]
Thank you so much for pointing me to the right place. I'm still very new to github.
self.demo.launch(share=True, auth=("username", "password"), show_error=True, server_name='0.0.0.0') results in an error

>    self.demo.launch(share=True, auth=("username", "password"), show_error=True, server_name='0.0.0.0')
  File "C:\Users\Tomoose\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 921, in launch
    raise ValueError(
ValueError: Cannot queue with encryption or authentication enabled.

**Comment by hlky** [comment]
error is self explanatory, queueing is enabled `demo.queue(concurrency_count=1)` and you can't use authentication and queuing

you'll have to disable one or the other

if you're trying to share this with friends and family and need queuing i would suggest a workaround to share and authenticate i.e. a reverse proxy

if you dont need queuing then simply comment out the demo.queue line

if you want to run this as saas you'll have to figure something else out, it's not an intended feature for this repo

**Comment by Tom-the-moose** [comment]
Pardon my ignorance. Thank you for helping me.
