### ISSUE TITLE
[BUG] missing required positional arguments: gobig_strength and gobig_step on img2img

### ISSUE THREAD

**Issue by YosAwed** [hlky/stable-diffusion-webui#411]
**Describe the bug**
When I run img2img generation,  File "scripts/webui.py", line 1428, in img2img
    output_images, seed, info, stats = process_images(
TypeError: process_images() missing 2 required positional arguments: 'gobig_strength' and 'gobig_steps'

**To Reproduce**
1. Go to 'Stable Diffusion image to image unified' Tab.
2. Input prompt
3. Click on '.Generate'

**Expected behavior**
img2img executed.

**Screenshots**
<img width="725" alt="img2img-error" src="https://user-images.githubusercontent.com/4214168/187816228-52b7d0e0-a358-4f8c-84ef-71ca5b10e116.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 104.0.1293.70 (official build) (64 bit)

**Comment by hlky** [comment]
GoBIG was removed a couple of days ago and only readded less than an hour ago, so I don't see how you could be having this issue unless your last update was at a misfortunate time and you haven't updated at all since.
