### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by JabiSanz** [hlky/stable-diffusion-webui#415]
I'm not sure what is the problem, I'm new here, last night i been using the generator without a problem but today when i tried to use it again, didn't work. The last step on colab lab stay for ever and don't work. I attached a screenshot with the issue. Please help, I have no idea what to do. Thanks in advance
![error](https://user-images.githubusercontent.com/111474301/187823579-03443feb-c9dc-43ee-b663-ade9231e2660.JPG)

**Comment by Tollanador** [comment]
It says it can't assign a GPU when loading GFPGAN, did you check that !nvidia-smi is showing a GPU?

**Comment by JabiSanz** [comment]
> It says it can't assign a GPU when loading GFPGAN, did you check that !nvidia-smi is showing a GPU?

I have no idea how to check, i been looking for answers on google but dont know how to fix it. I have no idea how to write code hehe!! Is about my nvidia graphic or the one in colab lab?

**Comment by JabiSanz** [comment]
> Colab issue

so what i should do? and also, i have to install and do all the process every time i want to run the generator, follow all the steps from the beginning or there is another way? thanks

**Comment by JabiSanz** [comment]
> Colab issue

is working now, thanks a lot. Btw i have to do all the steps every time i have want use it? I mean download etc...? Thanks
