### ISSUE TITLE
gradio module error? post the details of your setup here

### ISSUE THREAD

**Issue by hlky** [hlky/stable-diffusion-webui#42]
operating system:
> version (10, 11 etc), build (21h2 etc)
> language
> do you have git4windows installed?

conda
> did you install as all users?
> if you answered yes, are you sure?

stable-diffusion repo
> directory location
> directory listing (dir /b from cmd or cmd /c dir /b from powershell)
> first line of environment.yaml
> did the stable-refusion repo exist previously? or was it a fresh clone (as in the stable-diffusion directory did not exist at all until you did git clone or downloaded the zip)
> did you git clone or did you download the zip

launching
> run webui.cmd from cmd/powershell
> post the output from the line where you ran it to the first gradio error (do not post the repeated error messages... just once is fine)

Requested information could change, if you are asked to please post it again with the extra information

**Comment by heartlocket** [comment]
Trying to install and getting stuck in a module not found loop.

System info: Windows 11 Pro 64 bit 21H2 22000.856
I have a fresh anaconda install from a few days ago.
I had the previous model installed but installed

I already have the full version of anaconda installed, made sure that the script locations match the paths in webui. I followed instructions closely but every time i try and run webui i get stuck in an error loop:

Traceback (most recent call last):
File "C:\Users\heart\Desktop\DEV\stable-diffusion-main\stable-diffusion-main\scripts\webui.py", line 2, in
import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...

I have tried 'pip install gradio' before running it, this didnt help either.
help!!

my bad feel free to close my other issue reposting here

**Comment by ShinkoNet** [comment]
Did you change your environment.yaml's first line from ldm to something else?
If so, that's a step that should be removed from the rentry instructions.
For now, edit the text in webui.cmd and change ldm there to the word you changed in environment.yaml

**Comment by hlky** [comment]
> and ldm.cmd

Is it possible people are ignoring the instructions and trying to mix the shortcut and webui.cmd?

The shortcut (and ldm.cmd) is for ldm, webui.cmd is ldo, webuildm.cmd is ldm

Like you and I have already said, it seems likely that this issue is due to the instruction to change the environment.yaml, combined with the old guides still existing, and certain people's inability to read and follow the instructions

Alternatively, considering at least 2 (or 1 if its the same person) is having the issue with Windows 11, that it's a Windows 11 issue

**Comment by hlky** [comment]
Some user was running `webui.cmd` from conda, so that's another possible fix for anyone else, just double click it in the folder, or run it from cmd/powershell (I asked for this way for debugging because it would show all the output easier, and the output is still accessible - if the .cmd were to unexpectedly close the output is gone)

Glad to hear it's fixed though

**Comment by heartlocket** [comment]
Thanks!

**Comment by MarcusMcNut** [comment]
Here are the following changes that I needed to make to the yaml to get the WebUI to work.  I hope others will find this helpful.  I added gradio and pynvml to the pips and an -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion`
`name: ldo
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - gradio
    - pynvml
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion`

**Comment by hlky** [comment]
You needed to just use the environment.yaml, you must have been using an old repo, it already has all of that, and gfpgan, you're missing gfpgan from that.

I've removed that part of your comment to avoid confusion

**Comment by MarcusMcNut** [comment]
Hi I used the one from https://github.com/CompVis/stable-diffusion is there
a more recent repo?

**Comment by hlky** [comment]
you can't use webui.py with that repo, this is a fork that has made several changes to the environment.yaml to enable support for the new features added
Remove any old environment with conda env remove -n <name>  also just delete any stable-diffusion folders, dont forget to move the model.ckpt out beforehand otherwise you'll have to download it again, then start following the guide again from scratch
i'll ask the guide maintainer to clarify all of this in the guide to try and prevent these kind of issues occurring

**Comment by MarcusMcNut** [comment]
I'll give that a go in the morning, though with the changes I made to
environment it has been working. I'll do these steps tomorrow and hopefully
it will be even better!

**Comment by hlky** [comment]
Like I said you didn't need to change environment.yaml, if you downloaded stable-diffusion from [hlky/stable-diffusion](https://github.com/hlky/stable-diffusion) it already has everything required

[hlky/stable-diffusion-webui](https://github.com/hlky/stable-diffusion-webui) repo specifically is for the development of the webui and changes are synced to  [hlky/stable-diffusion](https://github.com/hlky/stable-diffusion) soon after being pushed here, a small delay allows for any bug fixes that are found after a push

i have asked the guide maintainer to not link directly to this repo because it's mainly for developers and evidently is causing issues where people think they can drop webui.py from [hlky/stable-diffusion-webui](https://github.com/hlky/stable-diffusion-webui) in anywhere and expect it to work (and also claim they followed the instructions to the letter, conveniently leaving out the part where they didn't)

**Comment by MarcusMcNut** [comment]
Yep, I'm going to start over in the morning, I should have realized when I
was thinking "huh how would this stay up to date then" that I'd screwed
something up.

**Comment by Muskelmagier** [comment]
I now know what in my case was the problem You have to type in "conda activate ldo" that fixes the whole problem.

**Comment by MarcusMcNut** [comment]
@hlky thank you for your help last night, I'm making sure to share the information with folks in the discord when they're running into the same issues as I, to be sure to use your stable-diffusion fork repo not this one.

**Comment by TwistedFromArma** [comment]
i too have the issue. I have used latest version and lmo change in the file.

**Comment by lozenge** [comment]
I just solved this problem on my own machine (Windows 10 Pro 20H2) by installing OpenSSL.

I specifically installed the "Win64 OpenSSL v1.1.1q Light" version from https://slproweb.com/products/Win32OpenSSL.html.

Hopefully this helps!

**Comment by hlky** [comment]
Discussion for this will move to 'Discussions'
Info to the Wiki

**Comment by ThisIsJustARandomGuy** [comment]
This just happened to me after doing a `conda clean --all` right after the first install. Deleting `z_version_env.tmp` and running `update_to_latest.cmd` solved it for me, in case anyone else runs into this.
