### ISSUE TITLE
[BUG] When batch or count > 1, SD generated images don't show up?

### ISSUE THREAD

**Issue by rexroth0619** [hlky/stable-diffusion-webui#429]
**Describe the bug**
Hi, WebUI works very well for me when I only generate 1 image with Stable Diffusion, but when I crank up batch or count number, the UI just hangs there. Here you can see it takes 20 seconds for 1 image, I chose to generate 4, but the UI just keeps loading indefinitely. However, images are actually generated successfully and saved in Google drive -- they just don't show up in WebUI.

Also, this behavior only begins with the second generation -- the first generation would work fine; multiple images will show up on UI if it's the first generation for the share link; but as soon as I want to generate multiple images again, it just hangs

**To Reproduce**
1. Deploy webui and get the Gradio share link
2. Generate image with multiple batches/counts for the first time
3. Profit!
4. Generate again with exactly the same settings with multiple batches/counts
5. UI hangs

I'm on Google Colab Pro

<img width="382" alt="Screen Shot 2022-09-01 at 5 37 29 PM" src="https://user-images.githubusercontent.com/4176960/187885051-013a1200-cd6e-4504-bb1d-401fe8f91c99.png">

<img width="1567" alt="Screen Shot 2022-09-01 at 5 44 45 PM" src="https://user-images.githubusercontent.com/4176960/187885288-8dea2ed9-5a5e-460f-8e44-0e52ea2bdc60.png">

**Comment by hlky** [comment]
This a known issue with Gradio and Colab, there's nothing that can be done yet afaik.
