### ISSUE TITLE
[FEATURE REQUEST] An option to retain the original image file (non-upscaled) when an upscaled image version is created

### ISSUE THREAD

**Issue by masslevel** [hlky/stable-diffusion-webui#434]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option (cli argument or interface option) to additionally keep the original output image file (non-upscaled version) if an upscaler (ex. RealESRGAN) is used in the chain

For example:
00000-50_k_lms_123123123123.png + 00000-50_k_lms_123123123123-esrgan4x.png

**Describe alternatives you've considered**
Creating a watchdog that makes a copy of the original output image file at the moment the file is created.

**Additional context**
In a previous webui build it saved both versions of the image but I think it was declared a bug. If the original image file can be kept as well, different processing methods can be applied to it in the future.

**Comment by hlky** [comment]
This won't be needed anymore, just waiting for some final changes to one pr then I'll merge the image processing tab to main repo, it has the upscalers and post-processors with batch support, that way everyone should be happy.
