### ISSUE TITLE
[BUG] Generated images get duplicated in the WebUI and the generated grid output

### ISSUE THREAD

**Issue by athu16** [hlky/stable-diffusion-webui#439]
**Describe the bug**
Generated images appear twice in the Web UI preview as well as the grid generated if "Save grid" is checked.
However the actual images are generated only once per seed, and the inference time is unchanged.

**To Reproduce**
1. Start the script with the --optimized flag (not sure if necessary).
2. Ensure "Save individual images" and "Save grid" are checked.
3. Enter a prompt and click "Generate".

**Expected behavior**
Each image appears only once in the Web UI as well as the generated grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/93036639/187927948-03844a4d-9717-4067-a564-f6851d3c5537.png)
![grid-00026-851956348_a_happy_tree_frog](https://user-images.githubusercontent.com/93036639/187928788-38a6995f-758b-4dc5-936e-e46c499aa48e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by HenkDz** [comment]
Having the same issue with regular image generation.

![image](https://user-images.githubusercontent.com/17301927/187932356-88f317df-0ad6-43f4-8781-8719a345dd2e.png)

**Comment by KyuubiYoru** [comment]
The problem seems to be with the "Save individual images" setting in Advance.

**Comment by HenkDz** [comment]
Untic "Save individual images"

![image](https://user-images.githubusercontent.com/17301927/187937381-41d3d4f9-dcce-438d-9e97-26fdc4dc43bd.png)
