### ISSUE TITLE
[BUG] image duplication in the graphical interface

### ISSUE THREAD

**Issue by Shark1337** [hlky/stable-diffusion-webui#443]
![image](https://user-images.githubusercontent.com/6165744/187936688-129a030f-1bc3-48ec-8519-02d7c70da993.png)

![image](https://user-images.githubusercontent.com/6165744/187937367-9d2b7f92-0af2-48e7-80d3-86cbfd792434.png)

the output are saved correctly are duplicated in the interface

thank you

**Comment by KyuubiYoru** [comment]
Duplicate with https://github.com/hlky/stable-diffusion-webui/issues/439
