### ISSUE TITLE
[Feature Request] Restore txt2image ESRGAN checkbox AND increase batch limit

### ISSUE THREAD

**Issue by rcyrus** [hlky/stable-diffusion-webui#445]
I will often like to generate a huge number of images while i'm doing other things and then cull them down to a selected few later on.

Recent changes removed the checkbox to apply upscaling automatically to each image AND the batch size slider has been reduced to 10 images. 

I know there was a bit UI update recently, is it possible to restore these features?

**Comment by ooofest** [comment]
I agree, the original idea to add the "Image Lab" was missing a usability consideration: we will often want to include upscaling as part of larger batch runs.  It is inconvenient to take multiple txt2img outputs and then manually push them through the Image Lab tab's processing.

The two concepts don't need to be mutually exclusive: bringing back GFPGAN and ESRGAN to the Text-to-Image tab will enhance user-friendliness and reduce time to process for many.

**Comment by flowerdealer** [comment]
Yeah I also want bigger batch numbers back.

**Comment by devilismyfriend** [comment]
The latest PR that got merged brought back those functions, enjoy.

**Comment by ooofest** [comment]
> The latest PR that got merged brought back those functions, enjoy. (not sure about the batch numbers)

Thank you - in the other thread, I mused about those functions somehow invoking the Image Lab options in an automated manner, to take advantage of its new/more detailed options.  I'm not sure how reasonable that is, but with the button that can manually push outputs to the Image Lab tab, it seemed reasonable to wonder if we could reuse its function by have txt2img runs send their outputs to the same tab and have them processed via a parm that triggers with latest/default options, as one idea.

**Comment by ooofest** [comment]
After some basic testing, the restored options do output expected images with the selected post-processing options, which is great!

Unfortunately, outputs do not display in the txt2img viewer when the GFPGAN and/or REalESRGAN options are checked.  Perhaps there is something else in the codebase that would need to be restored?

**Comment by hlky** [comment]
@ooofest those options were not intended to be added back in so they will not function

No one who uses these options could agree on what images they wanted displayed to the grid, gallery and which images they wanted saved. There would need to be an entire section of the ui to choose exactly which version of the image you want in the grid, in the gallery and whether each version is saved. The easiest solution is to just have it separate.

**Comment by ooofest** [comment]
@hlky While I appreciate that there are differences of opinion, and don't have an issue with the images not showing in the viewer at this time, removing this (again) as at least a functional option would add inconvenience to batch workflows and I appreciate what it offers now.  Having to manually process 20 outputs from a recent run in the Image Lab is rather an inconvenience, to say the least.

Which brings me back to my other post above: if the GFPGAN and ReadESRGAN options in the txt2img tag could push the SD outputs to the Image Lab function for processing in an automated/batched manner + their output, then I think that could solve the issue: you only see SD outputs in the txt2img viewer and the automated Image Lab outputs would be found in its output directory structure.
