### ISSUE TITLE
Go BIG (Upscaling using Stable Diffusion itself)

### ISSUE THREAD

**Issue by oldfndm** [hlky/stable-diffusion-webui#46]
> GoBIG is an upscaling technique, where a starting image is cut up into sections, and then each of those sections is re-rendered at a higher resolution. Once each section is done, they're all gathered and composited together, resulting in a new image that is 2x the size of the original.

https://github.com/lowfuel/progrock-stable

The main issue is probably adding one more requirement (realesrgan-ncnn-vulkan) and having people complain it doesn't work for them.

**Comment by hlky** [comment]
> The main issue is probably adding one more requirement 

That would be the main issue, there's other upscalers too, need to decide which one to implement, or several

#35 is semi-related, wants CodeFormer support in addition to gfpgan, again though, it could cause issues with people who don't update the environment.yaml after

**Comment by devilismyfriend** [comment]
would love to see this added, but also needs to be able to be used on existing images from the ui

**Comment by ZeroCool940711** [comment]
>it could cause issues with people who don't update the environment.yaml
You could add a line to the `webui.cmd` file to update the existing environment with any new dependencies added to the `environment.yml` file so when the user runs that script or the other that are similar the new dependencies are installed, probably adding `call conda env update --file environment.yml --prune` right after the line that creates the environment which is `call conda env create -f environment.yaml` should be enough for that, if the environment exist it wont be created but if there are new dependencies they will be installed.

**Comment by lendrick** [comment]
Why use the ncnn version of RealESRGAN when most people will already have the regular version of it installed?  Why would doing this add any requirements?
