### ISSUE TITLE
[Bug]:  Resize mode - only "Just resize"

### ISSUE THREAD

**Issue by VeyDlin** [hlky/stable-diffusion-webui#472]
### What happened?

![изображение](https://user-images.githubusercontent.com/10778537/188016965-3ba7b29e-29d9-4099-bf81-77ff50974105.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
Please describe the bug
