### ISSUE TITLE
[Bug]: When prompt text reaches the end of the field, focus is lost and ability to use 'enter/return' to submit is lost

### ISSUE THREAD

**Issue by nderscore** [hlky/stable-diffusion-webui#478]
### What happened?

#421 introduced a feature to automatically turn on multiline mode after the prompt text wraps.

When this happens, it triggers a fake click This takes focus out of the prompt field when it happens, requiring the user to click (or otherwise re-focus the prompt field) to resume typing.

This also breaks the ability to use the enter/return key to submit prompts

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
This isn't a bug, but an annoyance. 
Gradio replaces the input with a text area. 
This is on purpose so that longer prompts won't be hidden by the input. 

>This also breaks the ability to use the enter/return key to submit prompts

There's a setting for this and it's getting updated, restoring the setting resets that ability
