### ISSUE TITLE
Microsoft anti malware detects Trojan:Win32/Spursint.F!cl into this

### ISSUE THREAD

**Issue by paciox** [hlky/stable-diffusion-webui#481]
### What happened?

![image](https://user-images.githubusercontent.com/6546735/188031003-6cf9b2af-8389-4b66-bd4a-f4d28fbd8292.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Nobody else is having that issue. Make sure your `frontend/js/index.js` is the same as in this repo. Maybe it was compromised?

**Comment by altryne** [comment]
Closing this until further request, as @codedealer said we haven't seen these anywhere else

**Comment by paciox** [comment]
> Nobody else is having that issue. Make sure your `frontend/js/index.js` is the same as in this repo. Maybe it was compromised?

I took it from  the button code download from github here
