### ISSUE TITLE
[Bug]: image lab: the default configuration does not work

### ISSUE THREAD

**Issue by VeyDlin** [hlky/stable-diffusion-webui#483]
### What happened?

the default configuration does not work until you choose Upscale Models. I think the default check mark would solve this problem

Also, GoBig does not work at all

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment]
GoBig is fixed in an upcoming PR, there's no real way to know what the use is looking to do in the image lab, even more so once we'll add more stuff like animation etc, putting in defaults could be just as annoying as not putting them if you're not looking to upscale.

**Comment by VeyDlin** [comment]
oh, yes, then maybe should add notifications about the mandatory selection of the parameter and highlight the items that are not selected
