### ISSUE TITLE
[Bug]: img2img - Does not work if you leave the field empty

### ISSUE THREAD

**Issue by VeyDlin** [hlky/stable-diffusion-webui#484]
### What happened?

img2img does not work if you leave the field empty

If you have entered some text, after you have done at least one generation, then an empty field will work

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
This is how img2img works in SD
