### ISSUE TITLE
[idea]: add inpaint.py

### ISSUE THREAD

**Issue by VeyDlin** [hlky/stable-diffusion-webui#485]
### What happened?

inpaint.py a great tool, would like to see it!

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
Please add a suggestion in the discussions 
https://github.com/hlky/stable-diffusion-webui/discussions/categories/feature-suggestions
