### ISSUE TITLE
[idea]: Changing information when switching the slider

### ISSUE THREAD

**Issue by VeyDlin** [hlky/stable-diffusion-webui#486]
### What happened?

Sometimes, for a faster selection of results, I set small Sampling Steps. After that, I choose a good image and generate it with large Sampling Steps, this saves a lot of time.

But if you chose multiple generation, when switching the slider the information is not updated

I would like the seed to be updated as well when selecting another image, and even better if there was a button for copying the seed

It would also be convenient to create new tabs with the selected parameters in order to continue working with them separately

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
Please add ideas to discussion, the ones that the community will vote on will be picked up
