### ISSUE TITLE
[idea]: img2img - full resolution

### ISSUE THREAD

**Issue by VeyDlin** [hlky/stable-diffusion-webui#487]
### What happened?

In the official repository, when demonstrating the work of img2img a full-size image is used, it would be convenient to be able not to crop the image

![изображение](https://user-images.githubusercontent.com/10778537/188034785-9b2dfa72-6487-4dc2-9681-22cafa3a4976.png)
![изображение](https://user-images.githubusercontent.com/10778537/188034793-74936fa1-d24d-40e1-a556-3e2d92376d94.png)

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
Please suggest here: 
https://github.com/hlky/stable-diffusion-webui/discussions/categories/feature-suggestions
