### ISSUE TITLE
[Bug]:docker-compose.yaml error 

### ISSUE THREAD

**Issue by yangboz** [hlky/stable-diffusion-webui#490]
### What happened?

A bug happened!
```
services.stable-diffusion.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)
```

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
#123~18.04.1-Ubuntu

docker-compose version 1.17.1, build unknown
```

### Relevant log output

```shell
The Compose file './docker-compose.yaml' is invalid because:
services.stable-diffusion.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdBarho** [comment]
update docker compose to >= 1.28 [for gpu support](https://docs.docker.com/compose/gpu-support/#enabling-gpu-access-to-service-containers).

Also, prefer `docker compose` over `docker-compose`

**Comment by yangboz** [comment]
> for gpu support

even though upgrade docker compose version to "docker-compose version 1.28.3, build 14736152"
while ```docker compose up --build``` , it thrown: 
```
Step 7/12 : RUN wget -O ~/miniconda.sh -q --show-progress --progress=bar:force https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&     /bin/bash ~/miniconda.sh -b -p $CONDA_DIR &&     rm ~/miniconda.sh
 ---> Using cache
 ---> edb73db548a1
Step 8/12 : ENV PATH=$CONDA_DIR/bin:$PATH
 ---> Using cache
 ---> 59edf3b92e00
Step 9/12 : COPY /data/DejaVuSans.ttf /usr/share/fonts/truetype/
 ---> 6f4a5569c404
Step 10/12 : EXPOSE 7860
 ---> Running in 06ca622af4c3
Removing intermediate container 06ca622af4c3
 ---> 1f5275978a79
Step 11/12 : COPY ./entrypoint.sh /sd/
 ---> 28c13ef2a2c6
Step 12/12 : ENTRYPOINT /sd/entrypoint.sh
 ---> Running in 9695a5f09ebe
Removing intermediate container 9695a5f09ebe
 ---> c56aa54cce5a
Successfully built c56aa54cce5a
Successfully tagged stable-diffusion_stable-diffusion:latest
Recreating sd ... error

ERROR: for sd  Cannot start service stable-diffusion: could not select device driver "" with capabilities: [[gpu]]

ERROR: for stable-diffusion  Cannot start service stable-diffusion: could not select device driver "" with capabilities: [[gpu]]
ERROR: Encountered errors while bringing up the project.
```

**Comment by AbdBarho** [comment]
@yangboz do you have [NVIDIA Linux drivers](http://www.nvidia.com/object/unix.html) >= 418.81.07 installed? you can test that by typing `nvidia-smi` in a terminal.

it should output something like this:
```
[root@localhost release]# nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

You also need the nvidia container toolkit for your distribution, [install from here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).

You can test if your setup correct by running:
```
docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
```

**Comment by yangboz** [comment]
> @yangboz do you have [NVIDIA Linux drivers](http://www.nvidia.com/object/unix.html) >= 418.81.07 installed? you can test that by typing `nvidia-smi` in a terminal.
> 
> it should output something like this:
> 
> ```
> [root@localhost release]# nvidia-smi 
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
> | N/A   34C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```
> 
> You also need the nvidia container toolkit for your distribution, [install from here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).
> 
> You can test if your setup correct by running:
> 
> ```
> docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
> ```
I used this version driver.
```
cuda_11.6.0_510.39.01_linux.run
```

**Comment by AbdBarho** [comment]
@yangboz yes, can you try running `nvidia-smi` and tell me the output? also do you have the nvidia container toolkit? what version? if not, [install from here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).

If you have both, then run
```
docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
```
and show me the output

**Comment by yangboz** [comment]
> @yangboz yes, can you try running `nvidia-smi` and tell me the output? also do you have the nvidia container toolkit? what version? if not, [install from here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).
> 
> If you have both, then run
> 
> ```
> docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
> ```
> 
> and show me the output

Unable to find image 'nvidia/cuda:11.0.3-base-ubuntu20.04' locally
11.0.3-base-ubuntu20.04: Pulling from nvidia/cuda
d7bfe07ed847: Pull complete
75eccf561042: Pull complete
191419884744: Pull complete
a17a942db7e1: Pull complete
16156c70987f: Pull complete
Digest: sha256:57455121f3393b7ed9e5a0bc2b046f57ee7187ea9ec562a7d17bf8c97174040d
Status: Downloaded newer image for nvidia/cuda:11.0.3-base-ubuntu20.04
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by yangboz** [comment]
maybe the driver "" is incorrect , what's you guys' version? here is  nvidia A4000

**Comment by AbdBarho** [comment]
@yangboz You need to install nvidia container toolkit from here:

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

and restart your machine

**Comment by yangboz** [comment]
I fixit under https://collabnix.com/introducing-new-docker-cli-api-support-for-nvidia-gpus-under-docker-engine-19-03-0-beta-release/
