### ISSUE TITLE
[Bug]: image no longer displayed upon pressing generate

### ISSUE THREAD

**Issue by jjisnow** [hlky/stable-diffusion-webui#493]
### What happened?

When generating images on txt2image, although they are saved as files, the gallery view on the web page generated does not display an image, only a placeholder icon. This only happened in the last 2 days

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cobryan05** [comment]
https://github.com/hlky/stable-diffusion-webui/commit/1922a44334bc6ff22e930fa5601be72f6c75e694#diff-e093b909cce8fa9f0d7a77571607f8a1f9733c18d6e68ca2d03699c962df6fb5R943

Line 943 is the only output_images.append(image) left, and it only runs if not saving images.  Copy that line into in an 'else' from the 'if not skip_save' and you'll probably get your images back

**Comment by AdamNizol** [comment]
> [1922a44#diff-e093b909cce8fa9f0d7a77571607f8a1f9733c18d6e68ca2d03699c962df6fb5R943](https://github.com/hlky/stable-diffusion-webui/commit/1922a44334bc6ff22e930fa5601be72f6c75e694#diff-e093b909cce8fa9f0d7a77571607f8a1f9733c18d6e68ca2d03699c962df6fb5R943)
> 
> Line 943 is the only output_images.append(image) left, and it only runs if not saving images. Copy that line into in an 'else' from the 'if not skip_save' and you'll probably get your images back

Worked for me!
