### ISSUE TITLE
[Bug]: Number of Images Per Batch

### ISSUE THREAD

**Issue by sedetweiler** [hlky/stable-diffusion-webui#501]
### What happened?

I could run 250 images overnight without an issue, but now that I can only do 10 in a batch, I run out of memory and have to stop.  Please put this counter back to a higher number, as 250 was pretty awesome while I was sleeping.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sedetweiler** [comment]
This is a massive show-stopper for me.  Yesterday, I could run as many images as I wanted (up to 250) but in 1 batch.  If I run 2 batches, as you have warned, I run out of memory.  So, suddenly this went from 250 unique ideas overnight to 10.  I would kindly ask you to remove this restriction or tell me where I can change it myself.  This is a bit of a show-stopper for me, as I don't want to have to run a new batch every 10 images since my 3080 throws an error with more than 1.  I would, in fact, love to see a number slider larger than 250 so I can do my culling in the morning to determine what worked and where I want to explore with the image2image system.

**Comment by JoshB9999** [comment]
@sedetweiler if you are okay with editing the script yourself, you can change the upper limit in "frontend\frontend.py"
line 34 change 
`txt2img_batch_count = gr.Slider(minimum=1, maximum=10, step=1,`
to
`txt2img_batch_count = gr.Slider(minimum=1, maximum=250, step=1,`

**Comment by codedealer** [comment]
@sedetweiler you can modify the batch count to any value you want from the prompt window.
![image](https://user-images.githubusercontent.com/4258136/188106408-a6bf95d1-ac5c-479f-9887-f5a878c8e097.png)
continue typing and it should automatically take your argument
![image](https://user-images.githubusercontent.com/4258136/188106512-b2ca738b-95e4-4306-88c8-c3ae0a56839a.png)

**Comment by sedetweiler** [comment]
I will do this and thank you for the fix.  I am not sure why you nerfed one of the most impressive features of this system.  Since few can use more than one batch, this "number of images" is the key to making it work locally for most people.  You should see how much amazing stuff I can get overnight with this! This feature made this the best sd-gui out there.  I will just have to remember to change it each time I do a pull.

**Comment by Hadmos** [comment]
does this hack no longer work?
