### ISSUE TITLE
[Bug]: Error loading LDSR module

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [hlky/stable-diffusion-webui#505]
### What happened?

I did a fresh install/pull of your repo, installed ESRGAN and GFPGAN, then installed LDSR (git clone https://github.com/devilismyfriend/latent-diffusion.git into src directory and then copy the model.ckpt and project.yaml into stable-diffusion\src\latent-diffusion\experiments\pretrained_models. Is this the correct location for project.yaml?)

When I run the webui.cmd script I get the error:

```
Error loading LDSR:
Traceback (most recent call last):
  File "scripts/webui.py", line 359, in try_loading_LDSR
    LDSR = load_LDSR() # TODO: Should try to load both models before giving up
  File "scripts/webui.py", line 286, in load_LDSR
    from LDSR import LDSR
ModuleNotFoundError: No module named 'LDSR'
```

In the WebUI's image lab I still see the message: "Please download LDSR to activate more upscale features, instructions are available at the [Github](https://github.com/hlky/stable-diffusion-webui)" - Also note, there are no instructions for installing LDSR at that link.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdBarho** [comment]
@GalaxyTimeMachine did you clone this LDSR repo? https://github.com/devilismyfriend/latent-diffusion

**Comment by GalaxyTimeMachine** [comment]
@AbdBarho Yes I did. I'll correct the description, I said pull instead of clone.

**Comment by DJPatron** [comment]
Have you tried to launch ./latent-diffusion/blob/main/download_model.bat?
![image](https://user-images.githubusercontent.com/67385488/188210578-5f7dcf6b-ae1b-40f0-933a-986279849f05.png)

**Comment by HenkDz** [comment]
you followed [these steps](https://github.com/hlky/stable-diffusion-webui#ldsr) strictly?

**Comment by GalaxyTimeMachine** [comment]
> 

Yes.

**Comment by GalaxyTimeMachine** [comment]
I've just deleted everything, uninstalled Anaconda, then reinstalled everything, used miniconda this time...and now it all seems to be working!  :)

**Comment by tamueller** [comment]
I also need some help with this: The docu says I should download [project.yaml](https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1) and [model last.cpkt](https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1). and add them to src/latent-diffusion/experiments/pretrained_models/ which does not exist. You're mentioned to clone a github repository, which is not mentioned in the orginal docu.
Is there a complete step by step for this anywhere?
