### ISSUE TITLE
Cancel current job/generation

### ISSUE THREAD

**Issue by Mary-Usagi** [hlky/stable-diffusion-webui#51]
Hi :)

Is there a button that cancels the current generation that I'm too blind to find? Sometimes I accidentally generate too many images and have to wait forever for it to finish or quit and restart the whole script. It would be really great if there were a button to just straight up cancel the current generation (and maybe - to be extra fancy - display the results that finished generating before cancelling).

Thanks!

**Comment by hlky** [comment]
it would be a nice feature, best option atm if you're using using relauncher is to just ctrl c in the console window and it will restart automatically 
if you use webui.cmd you're using relauncher (webui.cmd opens relauncher)

**Comment by hlky** [comment]
Probably not possible with gradio

Reopen if new information regarding this issue comes up
