### ISSUE TITLE
[Bug]: Masks are offset

### ISSUE THREAD

**Issue by Dravoss** [hlky/stable-diffusion-webui#512]
### What happened?

Mask are offset, regenerating the area to the left of the masked zone, even in 1:1 images.
[https://imgur.com/a/QWNi5cK](url)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
Please update the link
