### ISSUE TITLE
img2img UI mask area sometimes show incorrect aspect ratio

### ISSUE THREAD

**Issue by LiJT** [hlky/stable-diffusion-webui#52]
https://imgur.com/a/gLtKYMf

Screenshot are shown above.

Masking: No matter which image i put in, it sometimes show wrong aspect ratio, always reset to square but not landscape or portrait.
Cropping: image always too small.

**Comment by hlky** [comment]
> image always too small.

dont crop it so small then...

**Comment by LiJT** [comment]
> > image always too small.
> 
> dont crop it so small then...

I didnt crop it, leaved as it is. anyway its not a huge issue. But masking panel definitely need some tweet, It never happened before, the latest update brought this problem. Thank you dev

**Comment by hlky** [comment]
```
The masking/cropping is very temperamental. It may take some time for the image to show when switching from Crop to Mask. If it doesn't work try switching modes again, switch tabs, clear the image or reload.
```

It's to be expected because masking and cropping in the same Image component is extremely experimental

**Comment by LiJT** [comment]
> ```
> The masking/cropping is very temperamental. It may take some time for the image to show when switching from Crop to Mask. If it doesn't work try switching modes again, switch tabs, clear the image or reload.
> ```
> 
> It's to be expected because masking and cropping in the same Image component is extremely experimental

Thank you dev you are awesome!

**Comment by hlky** [comment]
going to look at the masking aspect ratio now, is the result affected as well? does it look squished or anything?
