### ISSUE TITLE
Error using textual_inversion checkpoints

### ISSUE THREAD

**Issue by TriigerHappy** [hlky/stable-diffusion-webui#53]
I am currently using Colab Pro (assigned a T4 while experiencing these issues) and am getting an error when attempting to generate an image while I have a textual inversion checkpoint uploaded. The error is: 
Index put requires the source and destination dtypes match, got Half for the destination and Float for the source

All other functions are working perfectly as long as I haven't uploaded a checkpoint.

**Comment by hlky** [comment]
>got Half for the destination and Float for the source

run in full precision

>Colab Pro

no support for actual usage on  Colab Pro by me, if you can't figure out how to run in full precision thats not my problem
