### ISSUE TITLE
[Bug]: img2img uncrop produces black pixels outside the uncrop area

### ISSUE THREAD

**Issue by darthdeus** [hlky/stable-diffusion-webui#530]
### What happened?

When uncropping the missing part of the image remains black instead of being filled in with inpainting

![image](https://user-images.githubusercontent.com/123374/188217190-8bcef65d-bd74-43e8-9e91-a3e441a8f08d.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
Not a bug, just how img2img works.

**Comment by darthdeus** [comment]
I'm confused though, isn't this what everyone has been doing with outpainting? e.g. https://twitter.com/wbuchw/status/1565740716927623168

**Comment by TristanMorelle** [comment]
this is why fill needs to come back like discribed here

https://github.com/hlky/stable-diffusion-webui/raw/master/images/resizing.jpg
