### ISSUE TITLE
[Bug]: TypeError: __init__() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by dineshdharme** [hlky/stable-diffusion-webui#535]
### What happened?

I use the following command to start the WebUI

python webui.py --realesrgan-dir "Real-ESRGAN" --gfpgan-dir "GFPGAN" --defaults "webui.yaml"

I got the following error. It's not limiting me in any way. I just remove the `device` argument from the call. 

Loaded GFPGAN
Error loading RealESRGAN:
```
Traceback (most recent call last):
  File "webui.py", line 346, in try_loading_RealESRGAN
    RealESRGAN = load_RealESRGAN(model_name) # TODO: Should try to load both models before giving up
  File "webui.py", line 327, in load_RealESRGAN
    instance = RealESRGANer(scale=2, model_path=model_path, model=RealESRGAN_models[model_name], pre_pad=0, half=not opt.no_half, device=torch.device(f'cuda:{opt.gpu}'))
TypeError: __init__() got an unexpected keyword argument 'device'

```

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mchaker** [comment]
I faced this too:
https://github.com/hlky/stable-diffusion-webui/issues/431

**Comment by mchaker** [comment]
On 1 GPU only, it seems to cause no problems.

With multiple GPUs, it forces something to run on gpu 0 no matter what GPU i ask it to run on :(

**Comment by dineshdharme** [comment]
I have only 1 gpu.

**Comment by hlky** [comment]
Esrgan changed some code it seems, should work now
