### ISSUE TITLE
[Bug]: http error when running install

### ISSUE THREAD

**Issue by Lop010** [hlky/stable-diffusion-webui#536]
### What happened?

When i tried to run the `conda env create -f environment.yaml`command this error happend

`Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/pytorch/win-64'`

I have retried multiple times

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
(base) D:\ai\stable-diffusion-main(1)\stable-diffusion-main>conda env create -f environment.yaml
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/pytorch/win-64'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
This seems to be a local issue to your network, closing this until we see others like this, but I've installed our conda countless times today, the URL works.
