### ISSUE TITLE
txt2imghd: Generate high-res images with Stable Diffusion

### ISSUE THREAD

**Issue by Muskelmagier** [hlky/stable-diffusion-webui#54]
There is a interesting feature in another Fork

https://www.reddit.com/r/StableDiffusion/comments/wxm0cf/txt2imghd_generate_highres_images_with_stable/

maybe get in contact with them

**Comment by LiJT** [comment]
Cant wait!!!!

**Comment by RichardShannon** [comment]
Noticed this feature on reddit. 100% can't wait to see it in this fork.

**Comment by parsec501** [comment]
Wow, it really works marvelously

![jy5yy163nwj91](https://user-images.githubusercontent.com/105080989/186929698-ec1ca780-c950-46ca-8735-3a4da51df506.png)
![kg2uk4f2nwj91](https://user-images.githubusercontent.com/105080989/186929754-61ebffcc-e6a1-4b06-8560-a6a805c6d6f0.png)

**Comment by oldfndm** [comment]
This is the same as #46. Now that RealESRGAN is kinda included in the repo, it should be even easier to port.
