### ISSUE TITLE
[Bug]: img2img mask not working on images that arent 512x512

### ISSUE THREAD

**Issue by AdamNizol** [hlky/stable-diffusion-webui#543]
### What happened?

When doing the inpainting on a wide image it's not properly masking it and instead seems to be taking the mask, squishing it into 512x512 and applying img2img to only a portion of the image based on the squished mask. I used a fish that I generated which is 832x448 and I used img2img on the fish but I can see in the results that the part replaced is incorrect and where the fin is painted isn't regenerating like it should be, but a section to the left of it which shaped like a squished version of the fin, is generating when it shouldnt. I cant see the underlying mask but it seems to not be working properly for non-square images and from what I can tell is being squished and positioned on the left

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
width: 832
height: 448
blur: 2
sample steps: 50
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
Yes, non-square mask is not applied correctly. It has never been applied correctly, the image editor is extremely experimental has is only causing issues whereby people complain when things that could be done in an external tool (photoshop) aren't working in this project's extremely limited image editor, this project is not an image editor, it is a user interface for stable diffusion.
Please respect the limitations of the project, and refrain from complaining about issues that can be resolved simply by not expecting this webui to do them and using the appropriate tools.

**Comment by AdamNizol** [comment]
> Yes, non-square mask is not applied correctly. It has never been applied correctly, the image editor is extremely experimental has is only causing issues whereby people complain when things that could be done in an external tool (photoshop) aren't working in this project's extremely limited image editor, this project is not an image editor, it is a user interface for stable diffusion. Please respect the limitations of the project, and refrain from complaining about issues that can be resolved simply by not expecting this webui to do them and using the appropriate tools.

I wasn't trying to complain, I just figured I would explain the bug I had in case you werent aware. I didn't realize that we could make the masks separately though. Do I need to enable something in the settings to allow me to upload the mask or something? I dont see the option or documentation for it which is why I assumed the UI worked. Ultimately uploading my own mask would be ideal anyway. Would white or black part be the part kept in a mask? Or do you just convert the opacity channel into the mask?
