### ISSUE TITLE
[Bug]: Idk what happend, before it worked for me

### ISSUE THREAD

**Issue by Aesio91** [hlky/stable-diffusion-webui#545]
### What happened with google colab?

This appear.
Iteration: 1/1
100% 50/50 [00:19<00:00,  2.51it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 998, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 923, in process_images
    grid = image_grid(output_images, batch_size)
  File "scripts/webui.py", line 419, in image_grid
    fnt = get_font(30)
  File "scripts/webui.py", line 401, in get_font
    raise Exception(f"No usable font found (tried {', '.join(fonts)})")
Exception: No usable font found (tried arial.ttf, DejaVuSans.ttf)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Exspiravit** [comment]
i have the same error

**Comment by altryne** [comment]
This is on colab?

**Comment by Aesio91** [comment]
> This is on colab?

yeah, And I tried on mobile and pc :(

**Comment by altryne** [comment]
Colab was fixed, please reload from the repo and try again, that was my bad, I forgot to comment it back in

**Comment by Aesio91** [comment]
> Colab was fixed, please reload from the repo and try again, that was my bad, I forgot to comment it back in

wow so quick, thank you :)

**Comment by semlar** [comment]
This does not appear to be fixed.

The code to download the font file is incorrectly indented to be nested underneath the "if add_LDSR" block in the upscaler section of the setup, which means it won't download (an apparently critical font file?) unless "add_LDSR" is manually checked by the user.

**Comment by Gabriela-hub-89** [comment]
I have the same error

**Comment by kitckso** [comment]
> I have the same error, could you fix it?

Section 1.3, remove indentation of last 2 lines:
%cd /content/stable-diffusion/
!wget https://github.com/matomo-org/travis-scripts/blob/master/fonts/Arial.ttf?raw=true -O arial.ttf

**Comment by altryne** [comment]
> > I have the same error, could you fix it?
> 
> Section 1.3, remove indentation of last 2 lines: %cd /content/stable-diffusion/ !wget https://github.com/matomo-org/travis-scripts/blob/master/fonts/Arial.ttf?raw=true -O arial.ttf

I swear I tested it twice, the indentation is wrong?

Looking now

**Comment by kitckso** [comment]
> > > I have the same error, could you fix it?
> > 
> > 
> > Section 1.3, remove indentation of last 2 lines: %cd /content/stable-diffusion/ !wget https://github.com/matomo-org/travis-scripts/blob/master/fonts/Arial.ttf?raw=true -O arial.ttf
> 
> I swear I tested it twice, the indentation is wrong?
> 
> Looking now

Checked it is correct now.
