### ISSUE TITLE
[Bug]: GFPGAN causing major desaturation in faces

### ISSUE THREAD

**Issue by sedetweiler** [hlky/stable-diffusion-webui#548]
### What happened?

This is a show-stopper for using GFPGAN in the system for me.  With so much of the color gone, I need to merge every image with the original and use color restoration.  So, it is easier to use another GFPGAN on hugging face even though that is a bit of a pain, it is a lot less pain.  I have no idea if this is related to the color management handing issue we are seeing with the looping shifting to magenta.

Example: https://imgur.com/a/Y9iceeI

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Custom settings

```shell
Seems to be pervasive.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment]
This isn't a bug, GFPGAN fixed what he saw needs fixing and deemed your stylistic photo be wrong, the magenta color thing is unrelated to this

**Comment by sedetweiler** [comment]
> 

I don't believe this is the case, as I can use GFPGAN in another colab or on another site, and it works as expected.  Only on this branch so I have the desaturation issue.

**Comment by C-D-Harris** [comment]
In my experience, this always happened when going back to fix the images later in the GFPGAN tab. It worked as expected when GFPGAN was automatically applied during image generation.

**Comment by sedetweiler** [comment]
> 

All of my examples were done later, so your observation also agrees with my experiences.

**Comment by hlky** [comment]
Not a bug, just a side effect of using gfpgan.

> looping shifting to magenta.
This isn't a bug either, just a side effect of using loopback instead of getting the effect you actually want by doing the process manually 😉

**Comment by sedetweiler** [comment]
This is NOT a normal side effect of GFPGAN, as all other GFP systems produce the expected result.  See this example of 3 instances of GFPGANs as well as the original. https://imgur.com/a/BNVsy0e

**Comment by sedetweiler** [comment]
> 

This has already been shown to be a bug in the handling of the RGB values and should be done in another color space.  Regardless, it makes this part of the systemabsolutly useless.

**Comment by devilismyfriend** [comment]
@hlky seems like they were right, there's a desaturation issue stemming from PIL and how it handles RGBA, I added a convert to cv2 and applied it to GFPGAN, it's included in this PR https://github.com/hlky/stable-diffusion-webui/pull/584

**Comment by sedetweiler** [comment]
I think this was also only happening when done as a secondary operation and not when the initial image was created, and the "GFPGAN" option was checked.

**Comment by devilismyfriend** [comment]
I applied the fix to both just in case.
