### ISSUE TITLE
[Bug]: Cannot launch via webui.cmd or webuildm.cmd

### ISSUE THREAD

**Issue by Shazza-UX** [hlky/stable-diffusion-webui#550]
### What happened?

As stated cannot launch via webui.cmd or webuilmd.cmd. Getting the following issue everytime 

ModuleNotFoundError: No module named 'antlr4'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...

This does not seem to 
resolve itself and will continue in this loop 

I can run it via miniconda if I use this first: pip3 install antlr4-python3-runtime==4.9 

However everytime I shut it down,.. when I open it I must update all in the environment, and run pip3 install antlr4-python3-runtime==4.9 . After that if I run: python scripts/webui.py  It will launch correctly. 

Have tried multiple versions and even completely uninstalling it along with miniconda, but I keep getting this issue everytime

[antlr4.txt](https://github.com/hlky/stable-diffusion-webui/files/9481791/antlr4.txt)
[RunningViaMiniconda3.txt](https://github.com/hlky/stable-diffusion-webui/files/9481792/RunningViaMiniconda3.txt)

PS, sorry i am not really fluent in code, python or conda. I hope I constructed this issue correctly to be looked into. 

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 70, in <module>
    from omegaconf import OmegaConf
  File "C:\Users\spies\.conda\envs\ldo\lib\site-packages\omegaconf\__init__.py", line 1, in <module>
    from .base import Container, DictKeyType, Node, SCMode
  File "C:\Users\spies\.conda\envs\ldo\lib\site-packages\omegaconf\base.py", line 9, in <module>
    from antlr4 import ParserRuleContext
ModuleNotFoundError: No module named 'antlr4'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
Looks like an with your installation, not a bug.
