### ISSUE TITLE
[Bug]: The system cannot find the file custom-conda-path.txt.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [hlky/stable-diffusion-webui#558]
### What happened?

I have just done a fresh install and installed miniconda without changing any settings.

When I run webui.cmd I just get the following message:

`PS F:\stable-diffusion> .\webui.cmd
The system cannot find the file custom-conda-path.txt.
PS F:\stable-diffusion>`

Is this because the script isn't allowing for me having stable-diffusion on my F: drive and conda in C:\Users\{username}\miniconda3 ?

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GalaxyTimeMachine** [comment]
This is definitely caused by changes in the webui.cmd file. I copied the section that defines the paths from an older version into this one, and that works. I'm afraid I don't know enough to identify the exact cause, though.

**Comment by percimar** [comment]
Having the same issue here, I have miniconda installed at C:\ProgramData\miniconda3

Yeah seems like the cause is this PR hlky/stable-diffusion#191

**Comment by Delivator** [comment]
Yeah got the same issue

**Comment by xieve** [comment]
Curiously, webuildm.cmd works on my machine. These two files should probably be modularized as wrappers for a third file containing all the shared code.

**Comment by GalaxyTimeMachine** [comment]
The fix has improved things, but the error shows before it runs:

`(base) PS F:\stable-diffusion> .\webui.cmd
The system cannot find the file custom-conda-path.txt.
anaconda3/miniconda3 detected in C:\ProgramData\miniconda3
Collecting package metadata (repodata.json): done
...`
