### ISSUE TITLE
[Bug]: Text2img works, Img2img not working

### ISSUE THREAD

**Issue by iChristGit** [hlky/stable-diffusion-webui#564]
### What happened?

Hey, I am trying to install it using the guide, but it fails. the first part of the log is the error in load up and then trying a img2img and failing.
what am i doing wrong?

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
fresh install
```

### Relevant log output

```shell
Relauncher: Launching...
Warning: pyperclip is not installed. Pasting settings is unavailable.
Found GFPGAN
Found RealESRGAN
LDSR not found at path, please make sure you have cloned the LDSR repo to ./src/latent-diffusion/
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
Exception processing job JobInfo(inputs=('new york', 'Mask', None, 0, 3, 50, 'k_lms', [1, 4], 'RealESRGAN_x4plus', 1, 5, 0.75, None, 512, 512, 0, None), func=<function img2img at 0x000001B854CB0DC0>, session_key='"a95b51da80b440b2871a1c4c65174f68"', job_token=0, images=[], should_stop=<threading.Event object at 0x000001B859F365E0>, job_status="Error: 'NoneType' object is not subscriptable", finished=False, removed_output_idxs=[0]): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 611, in postprocess_data
    block.postprocess(prediction_value)
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 673, in postprocess
    return self.round_to_precision(y, self.precision)
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 563, in round_to_precision
    return float(num)
ValueError: could not convert string to float: '7d133a73b9134b2fa4fe4a5ee371ab1a'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iChristGit** [comment]
Tried new install, txt2img seems to work img2img not working:

Exception processing job JobInfo(inputs=('smart', 'Mask', None, 1, 3, 50, 'k_lms', [1, 4, 5, 6, 7], 'RealESRGAN_x4plus', 1, 5, 0.75, None, 512, 512, 0, None), func=<function img2img at 0x000001DA0E4E1550>, session_key='"7d9b8ccc5c224828a9dcf19ca627c40c"', job_token=0, images=[], should_stop=<threading.Event object at 0x000001DA192A39A0>, job_status="Error: 'NoneType' object is not subscriptable", finished=False, removed_output_idxs=[0]): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 611, in postprocess_data
    block.postprocess(prediction_value)
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 673, in postprocess
    return self.round_to_precision(y, self.precision)
  File "C:\Users\Osher\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 563, in round_to_precision
    return float(num)
ValueError: could not convert string to float: '3dbbd1b2ea2b42b8a17ecd05e0845b1b'

**Comment by AbdBarho** [comment]
Same as #565 #559

**Comment by iChristGit** [comment]
I dont see any other ".conda\envs\ldo\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}" errors, it might be something with my setup?
it did work before

**Comment by devilismyfriend** [comment]
@cobryan05 
looks like this has to do with https://github.com/hlky/stable-diffusion-webui/pull/460 , it's failing with the info generation

**Comment by cobryan05** [comment]
It looks like that happens if you don't type a prompt in. It's probably offsetting something in an array somewhere. I'll see if I can find why this happens, but I think it will go away if you type in a prompt.

**Comment by cobryan05** [comment]
I made a patch to print the true callstack of an exception, so that it doesn't look like everything comes from JobManager :laugh:

Went ahead and added a patch to fix the underlying issue, which is that empty prompts weren't working: https://github.com/hlky/stable-diffusion-webui/pull/590
