### ISSUE TITLE
[Bug]: A clean install on Windows stall on "Installing pip dependencies"

### ISSUE THREAD

**Issue by Eoinocal** [hlky/stable-diffusion-webui#585]
### What happened?

I'm using a full Anaconda install, not Miniconda. I'm tried creating the conda environment with `conda env create -f environment.yaml` but it only gets as far as 

    Collecting package metadata (repodata.json): done
    Solving environment: done
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done
    Installing pip dependencies: |

and the indicator keeps spinning. I have left this go for hours just in case it's ment to be that slow.

I have been able to get the original stable-diffusion repo working. I deleted it, and it's conda environment, before attempting this in case there might have been conflicts.

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OtherOfIce** [comment]
I had this problem.
If there's any sort of prompt needed, it doesn't show the prompt and just hangs from what I can tell.

I downloaded the models before the code had been pulled down (So made the folders manually)
This caused the hang, I just moved them out the way and it seemed to work.

**Comment by hlky** [comment]
This can be caused by having 'src' folder existing. You didn't try to create folders before like @OtherOfIce ?

**Comment by jjisnow** [comment]
Could be related to this (https://github.com/nicolai256/Stable-textual-inversion_win/issues/3)

**Comment by Eoinocal** [comment]
I tried [OtherOfIce](https://github.com/OtherOfIce)'s suggestion of not having the downloaded models present and then it worked perfectly! Thanks.

**Comment by AkioKiyota** [comment]
i did not get how did you guys solved it... i ddint downloaded any models just yet i am just following this tutorial 

https://www.howtogeek.com/830179/how-to-run-stable-diffusion-on-your-pc-to-generate-ai-images/

i have cloned the github page and then run 

```
conda env create -f environment.yaml
```
