### ISSUE TITLE
[Bug]: Doesn't display multiple images

### ISSUE THREAD

**Issue by gragland** [hlky/stable-diffusion-webui#588]
### What happened?

If I increase batch count or batch size beyond 1 then the UI displays the loading indicator indefinitely and never shows the images. I can tell the image are generated because the colab notebook indicates it finished and I can see the images being added to google drive.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Colab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
Colab / Gradio issue.
