### ISSUE TITLE
Scripts for batch prompt processing

### ISSUE THREAD

**Issue by JohannesGaessler** [hlky/stable-diffusion-webui#59]
Once the specification of settings via YAML is on master I plan to write CLI scripts for automatically processing large amounts of prompts/settings.
If other people are also interested in these scripts I'll write Python scripts and document them.
If there is no interest I will simply hack something together for my personal use.

**Comment by hlky** [comment]
This is merged to master and synced to main repo now, there is interest in batch processing scripts #90 here too, same result for them as implementing api

**Comment by JohannesGaessler** [comment]
Related PR: https://github.com/hlky/stable-diffusion-webui/pull/111

I ended up expanding the specification of YAML files for `--cli` to allow for batch processing.
If users need a more elaborate logic they should just write a custom Python script.
