### ISSUE TITLE
[Bug]: GoBig error. Used to be IndexError but is now TypeError

### ISSUE THREAD

**Issue by dalmackay** [hlky/stable-diffusion-webui#591]
### What happened?

I saw that one of the latest updates was supposed to fix Gobig which i've been waiting for but it still doesnt work. default settings. 

Edit: actually its all upscale modes that give me this same error

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\dalli\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\dalli\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\dalli\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\dalli\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\dalli\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\dalli\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: imgproc() takes 14 positional arguments but 17 were given
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment]
update the LDSR repo

**Comment by dalmackay** [comment]
just did, and did last night as well. same error. am i supposed to use download_model.bat every time? i assumed the models would stay when i overwrite (im new to all this)

**Comment by devilismyfriend** [comment]
no, you're supposed to update to the lastest LDSR.PY that's on there and have the latest webui.py from this repo

**Comment by dalmackay** [comment]
same error. webui.py is from 9/03 1:07am. LDSR.py is from 9/02 4:49pm

**Comment by dalmackay** [comment]
dragging and dropping the repo update and replacing existing files wasnt replacing webui.py for some reason. i now have the one from 3 hours ago, but same error

**Comment by devilismyfriend** [comment]
did you update the frontend folder from this repo as well

**Comment by dalmackay** [comment]
i guess something got mixed up somewhere. i restarted with a fresh install of the repo using all the same downloads i already had and it works now. thank you
