### ISSUE TITLE
[Bug]: Resize and Fill crashes on usage in img2img

### ISSUE THREAD

**Issue by silverogar** [hlky/stable-diffusion-webui#608]
### What happened?

Any option doesn't seem to make any difference - neither editor mode nor resolution nor...

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
textual_inversion added as per instructions
```

### Relevant log output

```shell
Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 512, 512] to have 3 channels, but got 4 channels instead
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
>Resize and fill

You must be using an old version, this option was temporarily removed because it was causing issues.

img2img is currently being investigated, see #610
