### ISSUE TITLE
Issue with outside access 

### ISSUE THREAD

**Issue by jh28wd40** [hlky/stable-diffusion-webui#61]
Something has changed with how a public IP can work with Gradio. 

With (share=True) turned on or if I turn it off and just allow anyone from outside to call upon my public IP:7860. 

Sometimes you can press the submit button and SD will start sampling and you can see this in Condra, other times and most of the time submit does absolutely nothing.  I tried other browsers and devices too. 

If you go locally via the LAN to your computer or just the local host, it works just fine.  

This was something that just started happening with the newer version. 

I've tried removing and cleaning out the environment and reinstalling, but the same issue persists. 

Also, Is there any way we can create a simple password challenge? I would like to allow my close friends access via public, but obviously, keep out anyone that could try to put images on my computer that may not be appropriate.  I'm not talking about going all crazy SSL, but just something small that I could put in the webui.py. Just to make it a little harder. 

Thanks,

**Comment by hlky** [comment]
SaaS is not feature supported by me, you're on your own
