### ISSUE TITLE
[Bug]: Key error prompt.

### ISSUE THREAD

**Issue by ZeroCool22** [hlky/stable-diffusion-webui#619]
### What happened?

A bug happened!
![Screenshot_1](https://user-images.githubusercontent.com/13344308/188309875-269c5655-2c07-4f8b-8250-88c1ca46d101.jpg)

I was using a old version of the repo and there wasn't any problem, but today i just see the repo wasn't updating even if i have the **environment.yaml file**.

![Screenshot_2](https://user-images.githubusercontent.com/13344308/188309939-cd9bc37a-34d2-4a25-852e-8fab6763411b.jpg)

So i downloaded the updated files and replaced it, but now i have the error i shows in the screen... :(

![Screenshot_3](https://user-images.githubusercontent.com/13344308/188309976-640d68dd-d3d0-4eab-86aa-dc11ae4ba513.jpg)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
Not really.
```

### Relevant log output

```shell
Don't know where the log is stored.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool22** [comment]
The error makes mention of this line:

![Screenshot_4](https://user-images.githubusercontent.com/13344308/188310475-0addb6a2-b64c-4cbb-a31c-cc78dd86e80e.png)

**Comment by hlky** [comment]
Update properly from the main repo.
