### ISSUE TITLE
Disable Telemetry

### ISSUE THREAD

**Issue by tadev** [hlky/stable-diffusion-webui#62]
Gradio sends telemetry by default, adding analytics_enabled=false to the Interface definition disables this.
However I am not sure if it also works in the current way the WebUI is setup with "gradio.Blocks" demo.

`demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label", analytics_enabled=false)`

see: https://gradio.app/docs/ 

I also saw one of the older gradio interfaces connect to an amazon ec2 instance, possibly there's more telemetry to be disabled.

**Comment by hlky** [comment]
[1d4ece7](https://github.com/hlky/stable-diffusion-webui/commit/1d4ece76b8aafa6c75d4323386498ce0414ecf91) fixed
