### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by random29** [hlky/stable-diffusion-webui#63]
Thanks for your work!
 
Got an issue - pulled last webui.py, but after executing got this 
![image](https://user-images.githubusercontent.com/32632835/186923785-87622932-07f0-4602-9e6a-3196953e7cca.png)
error with any setting

**Comment by random29** [comment]
Fixed with latest commit, thanks

**Comment by hlky** [comment]
Honestly I dont know why glob isn't working, it should, root_dir is an argument for glob, changed it to use something else

This is dev version, you shouldn't be using this directly unless asked to or you don't mind being a bleeding edge beta tester. 

Sometimes like in this instance, a pr is actually broken despite any testing the author may or may not have done, it looked fine and the author said they had tested it, so I merged

Use the version from the [main repo](https://github.com/hlky/stable-diffusion) if you want stability

**Comment by random29** [comment]
Okay, will have in mind
