### ISSUE TITLE
[Bug]: Stable Diffusion Last version, out of memory error. (Old ones works fine with same settings).😒

### ISSUE THREAD

**Issue by ZeroCool22** [hlky/stable-diffusion-webui#650]
### What happened?

A short video showing the problem:

https://www.youtube.com/watch?v=Lo2MPkzCBio

Isn't supposed the new version works better and is more optimized, why give me out of memory error with the **exact same settings and resolution**?

📝Settings:

✅**optimized** = False
✅**optimized_turbo** = True

✅**Width**: 512 píxeles
✅**Height**: 768 píxeles

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
📝Settings:

✅**optimized** = False
✅**optimized_turbo** = True

✅**Width**: 512 píxeles
✅**Height**: 768 píxeles
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AscendedGravity** [comment]
Assuming you've also downloaded the latest files from the main repo, edit relauncher.py included in the scripts folder instead.

**Comment by ZeroCool22** [comment]
> Assuming you've also downloaded the latest files from the main repo, edit relauncher.py included in the scripts folder instead.

It did the trick man, a very big thx for you!

![Screenshot_1](https://user-images.githubusercontent.com/13344308/188344920-0d5579ca-c2e2-41a3-97a2-b68ddb89dfae.jpg)

I was scratching my head thinking why this could happen...
