### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by toniohc** [hlky/stable-diffusion-webui#66]
When you git clone RealESRGAN, the directory is Real-ESRGAN.
You must rename the directory or modify line 59 of webui.py

`parser.add_argument("--realesrgan-dir", type=str, help="RealESRGAN directory", default=('./src/realesrgan' if os.path.exists('./src/realesrgan') else './RealESRGAN'))`

by 

`parser.add_argument("--realesrgan-dir", type=str, help="RealESRGAN directory", default=('./src/realesrgan' if os.path.exists('./src/realesrgan') else './Real-ESRGAN'))`

**Comment by hlky** [comment]
>You must rename the directory 

This is the intended usage right now, realesrgan is for advanced users only right now
