### ISSUE TITLE
Generate/compare multiple sampling methods at once?

### ISSUE THREAD

**Issue by testingstuffout2** [hlky/stable-diffusion-webui#69]
In the readme it seems to imply that I can generate and compare three different sampling methods with txt2img.py at once - is that the case? If so - where is the option to enable that?

Referring to this: https://github.com/hlky/stable-diffusion-webui#sampling-method-selection

**Comment by hlky** [comment]
no... that's just an example showing 3 different sampling methods...

**Comment by testingstuffout2** [comment]
> no... that's just an example showing 3 different sampling methods...

would it be possible to generate 3 different sampling methods at once? that would be a neat feature, similar to the prompt matrix
