### ISSUE TITLE
Error when sending the generation

### ISSUE THREAD

**Issue by daswer123** [hlky/stable-diffusion-webui#71]
Hi, tried to run webui on google collab, no problem with installation, but it gives an error when trying to generate:

```
WebSocket connection to 'wss://27257.gradio.app/queue/join' failed: 
close
```
![image](https://user-images.githubusercontent.com/22278673/186942690-e1ae6162-1cbf-4264-8fd4-6de763a0c066.png)
![image](https://user-images.githubusercontent.com/22278673/186942630-2deffbdc-211f-4cad-8fe1-91472a2e15bf.png)

Is there any way to fix this?

Google Colab. 
https://colab.research.google.com/drive/1MfnpAl5BkIgegl2bImBzcASF71eN_ruS?usp=sharing

**Comment by hlky** [comment]
>Google Colab.

Completely unrelated to me, not my problem, ask creator of the colab
