### ISSUE TITLE
[Bug]: Docker build fails with error "The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Release' does not have a Release file."

### ISSUE THREAD

**Issue by AndreaPi** [hlky/stable-diffusion-webui#820]
### What happened?

I'm trying to build and run the Docker container for `stable-diffusion-webui`. To do this, I `cd` to the repo directory, and I run `docker-compose up -d`. I manage to dowload the base image, but the build process fails at this step:

```
Step 9/16 : RUN apt-get update &&     apt-get install -y libglib2.0-0 wget &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 377a88c04cf2
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Get:4 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2129 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Err:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 152.195.19.142 443]
Get:8 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [892 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1501 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [30.2 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1194 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2590 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1613 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [27.4 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.1 kB]
Reading package lists...
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Release' does not have a Release file.
```

Can you help? Thanks

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by outlookhazy** [comment]
looks like a certificate issue with the nvidia repository (Err:7), (re)building is working perfectly fine on my machine but I've already pulled that image.

**Comment by jadechip** [comment]
Are you building the image on a x86 system? Using an arm based system or an M1 Mac for example can cause this error.

**Comment by AndreaPi** [comment]
> looks like a certificate issue with the nvidia repository (Err:7), (re)building is working perfectly fine on my machine but it may be using a cached image. You can browse to that repository manually, there's definitely a Release file there

@outlookhazy it shouldn't be a certificate issue, certificates were recently fixed. But I'll look into it again. Thanks

**Comment by AndreaPi** [comment]
> Are you building the image on a x86 system? Using an arm based system or an M1 Mac for example can cause this error.

@jadechip no, it's a Linux server. Thanks anyway

**Comment by oc013** [comment]
Just built from scratch after destroying all images and volumes on this new repository and did not encounter this error.   Possibly network issues, are you still experiencing it if you try today?

**Comment by AndreaPi** [comment]
@oc013 I'm not in front of the laptop this weekend, but I'll make some tests tomorrow (or maybe even this evening)
