### ISSUE TITLE
Fixed "Generate Button" Position

### ISSUE THREAD

**Issue by HenkDz** [hlky/stable-diffusion-webui#87]
It would be great if you could make this button position:fixed 
![image](https://user-images.githubusercontent.com/17301927/186988310-af6db862-df0e-43fc-9dbb-58cce1926755.png)

**Comment by altryne** [comment]
This can be closed now, button sits at the prompt 
![CleanShot 2022-08-27 at 10 06 35@2x](https://user-images.githubusercontent.com/463317/187038361-ce3db23c-a705-4d3e-b6a4-70100ba0f5b7.jpg)

**Comment by search620** [comment]
if possible make it so that the user decides how to arrange the windows as he wish (drag&drop style)

**Comment by altryne** [comment]
@search620 open a feature request for this, but IMO it's not possible to drag/drop in gradio, and if it would be, it won't be saved for next launch
