### ISSUE TITLE
[Feature Request] Update image preview on Web UI during generation instead of at the end.

### ISSUE THREAD

**Issue by ZeroCool940711** [hlky/stable-diffusion-webui#95]
Hi there, first of all I would like to thank you for this awesome UI, its really easy to use and saves a lot of time compared to running everything from the console.
I think it would be nice if the image preview shown on the web UI would update as it is being generated instead of been shown at the end of the generation, this would be useful for images that take long to generate because of really high resolution, old GPU, too many options selected and for long batches of images. The ideal thing would be to get the image updated after each sampling step during the generation but if that's too much to ask then having the image been updated on the UI after each batch would be still better than the current way it's done. I know the images are saved on the output folder but having to manually go to the images every time can be not only annoying but time-consuming in the long run. Thanks for your time and again, thanks for this awesome web UI.

**Comment by hlky** [comment]
As far as I know this isn't possible due to the way gradio works, it doesn't output anything until our function finishes, which isn't until all images in the batch are generated

Can't you just wait for new files to appear in the directory they save to?

**Comment by ZeroCool940711** [comment]
I can wait for it and I usually do but if for example you are running long batches it takes forever, also, if you are connecting remotely to gradio from your phone or other device you are not able to access the files directly on the disk. 

Btw, is there any chance you could make a version of the UI using Streamlit? 
When I was using VQGAN+CLIP I was using one [app](https://github.com/tnwei/vqgan-clip-app) that was made using Streamlit and it was pretty good, streamlit does let you render almost during execution as long as you can just add one line inside the loop where the image is being generated, [here](https://github.com/tnwei/vqgan-clip-app/blob/82aff7993b5f64baacfe626e214398bad2d657d7/app.py#L157) for example is where that was happening.

**Comment by hlky** [comment]
Files are output after every batch, it's just the UI that doesn't update until it's finished, afaik it's a limitation of Gradio
As for accessing the files remotely there are many workarounds for that

> Streamlit

There are no immediate plans for a different base for the UI, but I will keep it in mind

**Comment by AK391** [comment]
there is a open issue to support iterative outputs for gradio: https://github.com/gradio-app/gradio/issues/776

**Comment by jjisnow** [comment]
https://github.com/sd-webui/stable-diffusion-webui/issues/446
