### ISSUE TITLE
Optimized version support discussion

### ISSUE THREAD

**Issue by oobabooga** [hlky/stable-diffusion-webui#97]
Someone posted this modified script on /g/, and it allowed me to run your script on my 4GB GPU:

```
okay, here it is: https://pastebin.com/AAi3Zw4T

notes:

don't ask me any questions lol, i don't know what i'm doing
put it in your scripts folder as webui.py or whatever
make sure you have the optimizedSD folder in your main dir, i load a config file from there
by default it still runs the normal way, to run the optimized mode you need the command line switch --optimized, so "python sctipts/webui.py --optimized"
if you're running via the cmd script i guess you want to edit the --optimized into relauncher.py

```
I had to run it with

`python scripts/supposed-webui-optimized.py --precision full --no-half`

I propose we keep this issue open until someone comes up with a clean pull request adding optimized support to this repo. This should be done through a new --optimized flag that keeps backward compatibility by default.

**Comment by hlky** [comment]
hold on

**Comment by hlky** [comment]
#98 just pushed
if you want to test, im about to

**Comment by oobabooga** [comment]
I'll test it now and report back

**Comment by oobabooga** [comment]
I run out of memory before the gradio interface is launched with or without --optimized:

`python scripts/webui.py --precision full --no-half --optimized`

This is the error

> Traceback (most recent call last):
>   File "scripts/webui.py", line 306, in <module>
>     model.cuda()
>   File "/home/zzz/.miniconda3/envs/ldo/lib/python3.8/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 127, in cuda
>     return super().cuda(device=device)
>   File "/home/zzz/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 689, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "/home/zzz/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/home/zzz/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/home/zzz/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   [Previous line repeated 7 more times]
>   File "/home/zzz/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
>     param_applied = fn(param)
>   File "/home/zzz/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 689, in <lambda>
>     return self._apply(lambda t: t.cuda(device))
> RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.82 GiB total capacity; 2.96 GiB already allocated; 8.25 MiB free; 3.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

For reference, if I run the pastebin script afterwards, it still works. I'm trying to figure out the difference.

**Comment by hlky** [comment]
gfpgan and esrgan are loaded to gpu by default as well

try 
`--gfpgan-cpu --esrgan-cpu` as well

i take it you have a 16xx series card that's why you need optimized but are running at full precision?

**Comment by oobabooga** [comment]
It's a GTX 1650, I started using full precision because the txt2img script on the basujindal repo would give me blank green images otherwise.

With `python scripts/webui.py --precision full --no-half --gfpgan-cpu --esrgan-cpu --optimized` the interface is successfuly launched but the script crashes due to lack of memory if I try to generate an image:

> !!Runtime error (txt2img)!! 
>  CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 3.82 GiB total capacity; 2.51 GiB already allocated; 32.25 MiB free; 2.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> exiting...calling os._exit(0)

If I remove `--optimized` from the command above while keeping `--gfpgan-cpu --esrgan-cpu`, the script crashes before gradio launches as before.

**Comment by oobabooga** [comment]
Wait! It does work with `python scripts/webui.py --precision full --no-half --optimized --gfpgan-cpu --esrgan-cpu`, I forgot to change the resolution from the default (max I could always use was 448x448). It seems to be working, I'll post a result in a sec

**Comment by hlky** [comment]
hang on, pull it again, i've just pushed

i compared to basujindal and cuda() got into a couple of places it shouldn't have been

because i didn't know what commit the person who made the pastebin 'fork' used i had to try to get just the optimized changes out in a funny way

**Comment by oobabooga** [comment]
![corgi](https://user-images.githubusercontent.com/112222186/187010605-f7dc2fcd-8a10-4948-90c5-21b33dd51230.png)

**Comment by oobabooga** [comment]
Let me try the updated version

**Comment by hlky** [comment]
![image](https://user-images.githubusercontent.com/106811348/187010636-ae5eced8-9196-424f-b603-e96ed0d6cc69.png)
yeah this is more like it

**Comment by oobabooga** [comment]
With the latest version I got this error after clicking on 'Generate' to generate an image from a prompt 

> Traceback (most recent call last):
>   File "/home/zzz/.miniconda3/envs/ldo/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
>     output = await app.blocks.process_api(
>   File "/home/zzz/.miniconda3/envs/ldo/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
>     predictions, duration = await self.call_function(fn_index, processed_input)
>   File "/home/zzz/.miniconda3/envs/ldo/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/home/zzz/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/home/zzz/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "/home/zzz/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "scripts/webui.py", line 797, in txt2img
>     output_images, seed, info, stats = process_images(
>   File "scripts/webui.py", line 557, in process_images
>     modelCS.to(device)
> NameError: name 'device' is not defined
> [MemMon] Recording max memory usage...
>

**Comment by hlky** [comment]
yeah sorry it was needed in 1 one place, it was kinda awkward to merge
pull again

**Comment by hlky** [comment]
![image](https://user-images.githubusercontent.com/106811348/187010970-60cee6c1-6a8b-4f09-af38-90d60bbe7019.png)

**Comment by oobabooga** [comment]
I confirm that everything is working now

`python scripts/webui.py --precision full --no-half --gfpgan-cpu --esrgan-cpu --optimized`
![xxx](https://user-images.githubusercontent.com/112222186/187011117-a7245653-8dfd-4f4d-b9ce-cd2d069384b6.png)

Thank you so much, you are brilliant!

**Comment by zillionsk8** [comment]
Can confirm updating `scripts/relauncher.py` with `python scripts/webui.py --precision full --no-half --gfpgan-cpu --esrgan-cpu --optimized` is fully working on laptop GTX1660ti generating 512x512 , upscaling and GFPGAN
